# Default and required variables for the "certbot" role.
#
# Commented-out variables must be defined elsewhere (in an inventory,
# playbook, or at runtime).
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A dictionary where keys are domain names to obtain certificates for.
# Each key can have an optional value consisting of a dictionary with
# the following key-value pairs:
#
#   - "aliases": A list of additional domain names to include when
#     obtaining a certificate.

certbot__certificates: {}


# A string containing the email address associated with a Let's Encrypt
# ACME account. An account will be created if the email address hasn't
# been previously registered.

# certbot__administrator_email: ''
