# The following role installs Rust-related bits and pieces with rustup.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Get status of rustup'
  ansible.builtin.stat:
    path: '/home/{{ rust__user_username }}/.cargo/bin/rustup'
  changed_when: false
  register: __rustup_binary

- name: 'Ensure rustup and friends are installed'
  when: not __rustup_binary.stat.exists
  block:
    - name: 'Ensure "rustup-init" is downloaded to a temporary location'
      ansible.builtin.get_url:
        checksum: '{{ rust__rustup_init_checksum }}'
        dest: '/tmp/rustup-init'
        group: '{{ rust__user_username }}'
        mode: '0755'
        owner: '{{ rust__user_username }}'
        url: '{{ rust__rustup_init_url }}'

    - name: 'Ensure rustup and friends are installed'
      ansible.builtin.command: '/tmp/rustup-init --no-modify-path -y'
      register: __rustup_init
      changed_when: __rustup_init.stdout is search('installing')
      become: true
      become_user: '{{ rust__user_username }}'
  always:
    - name: 'Ensure "rustup-init" is removed'
      ansible.builtin.file:
        path: '/tmp/rustup-init'
        state: 'absent'

- name: 'Ensure rustup and friends are up-to-date'
  ansible.builtin.command: '/home/{{ rust__user_username }}/.cargo/bin/rustup update'
  register: __rustup_update
  changed_when: __rustup_update.stdout | regex_search('(installed|updated)')
  become: true
  become_user: '{{ rust__user_username }}'
