# The following tasks perform a Capistrano-style website deployment.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Load variables from release artifact metadata YAML document'
  ansible.builtin.include_vars:
    file: '{{ deploy_to_vhost__release_artifact_folder }}/release.yml'
    name: __release_metadata

- name: 'Set virtual host base directory variable'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.set_fact:
    __vhost_base_directory: '/var/www/{{ deploy_to_vhost__site_domain }}'

- name: 'Set release base directory variable'
  ansible.builtin.set_fact:
    __release_base_directory: '{{ __vhost_base_directory }}/releases/{{ __release_metadata.release_timestamp }}'

- name: 'Check for an existing in-progress deployment'
  block:
    - name: 'Get status of an existing deployment lock file'
      ansible.builtin.stat:
        path: '{{ __vhost_base_directory }}/deploy.lock'
      register: __deploy_lock_status

    - name: 'Stop current deployment if a deployment is already in progress'
      ansible.builtin.fail:
        msg: 'A deployment is already in progress'
      when: __deploy_lock_status.stat.exists

- name: 'Ensure a deployment lock file exists'
  ansible.builtin.file:
    group: '{{ deploy_to_vhost__administrator_username }}'
    mode: 0640
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/deploy.lock'
    state: 'touch'

- include: 'preflight.yml'
- include: 'setup.yml'

- name: 'Create release base directory'
  ansible.builtin.file:
    group: 'www-data'
    mode: 0750
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __release_base_directory }}'
    state: 'directory'

- name: 'Unarchive release artifact archive into release base directory'
  ansible.builtin.unarchive:
    src: '{{ deploy_to_vhost__release_artifact_folder }}/release.tgz'
    dest: '{{ __release_base_directory }}'
  become: false

- name: 'Update owners and permissions of release directory contents'
  ansible.builtin.command: '{{ item }}'
  args:
    chdir: '{{ __release_base_directory }}'
  changed_when: true
  loop:
    - "find . -exec chown '{{ deploy_to_vhost__administrator_username }}:www-data' {} \\;"
    - "find . -type f -maxdepth 1 -exec chown '{{ deploy_to_vhost__administrator_username }}:root' {} \\;"
    - "find . -wholename './private*' -exec chown '{{ deploy_to_vhost__administrator_username }}:root' {} \\;"
    - 'find . -type d -exec chmod 0750 {} \;'
    - 'find . -type f -exec chmod 0640 {} \;'
    - "find . -type f -wholename './private/bin/*' -exec chmod 0750 {} \\;"
    - "find . -type f -wholename './private/cron/*' -exec chmod 0750 {} \\;"

- name: 'Add web-server-writable directories to release directory'
  ansible.builtin.file:
    path: '{{ __release_base_directory }}/{{ item }}'
    state: 'directory'
    owner: 'www-data'
    group: 'www-data'
    mode: '2750'
  loop: '{{ __release_metadata.writable_directories_release }}'
  when: __release_metadata.writable_directories_release is defined

- name: 'Ensure web-server-writable directories exist in shared directory'
  ansible.builtin.file:
    path: '{{ __vhost_base_directory }}/shared/{{ item }}'
    state: 'directory'
    owner: 'www-data'
    group: 'www-data'
    mode: '2750'
  loop: '{{ __release_metadata.writable_directories_shared }}'
  when: __release_metadata.writable_directories_shared is defined

- name: 'Check for and run project-specific pre-installation tasks'
  block:
    - name: 'Get status of project-specific pre-installation tasks file'
      ansible.builtin.stat:
        path: '{{ deploy_to_vhost__release_artifact_folder }}/pre-install-tasks.yml'
      changed_when: false
      register: __pre_install_tasks_file

    - name: 'Include project-specific pre-installation tasks file (if applicable)'
      ansible.builtin.include_tasks:
        file: '{{ deploy_to_vhost__release_artifact_folder }}/pre-install-tasks.yml'
      when: __pre_install_tasks_file.stat.exists

- name: 'Check for and install PHP dependencies with Composer'
  block:
    - name: 'Get status of "composer.json" in release directory'
      ansible.builtin.stat:
        path: '{{ __release_base_directory }}/composer.json'
      register: __composer_json

    - name: 'Slurp "composer.json" in release directory into a variable'
      ansible.builtin.slurp:
        src: '{{ __release_base_directory }}/composer.json'
      register: __composer_json_slurp
      when: __composer_json.stat.exists

    - name: 'Install PHP dependencies with Composer'
      community.general.composer:
        classmap_authoritative: true
        command: 'install'
        working_dir: '{{ __release_base_directory }}'
      become: false
      changed_when: true
      when: __composer_json.stat.exists

    - name: 'Update owners and permissions of vendor directory'
      ansible.builtin.command: '{{ item }}'
      args:
        chdir: "{{ __release_base_directory }}/{{ (__composer_json_slurp['content'] | b64decode | from_json)['config']['vendor-dir'] | default('vendor') }}"
      changed_when: true
      loop:
        - "find . -exec chown '{{ deploy_to_vhost__administrator_username }}:www-data' {} \\;"
        - 'find . -type d -exec chmod 0750 {} \;'
        - 'find . -type f -exec chmod 0640 {} \;'
      when: __composer_json.stat.exists

- name: 'Update environment Apache configuration file'
  ansible.builtin.template:
    dest: '{{ __vhost_base_directory }}/deployment.apache2.conf'
    group: 'root'
    mode: 0640
    owner: '{{ deploy_to_vhost__administrator_username }}'
    src: 'deployment.apache2.conf.j2'
  notify:
    - 'Reload Apache'
    - 'Reload PHP-FPM'

- name: 'Update environment Bash shell configuration file'
  ansible.builtin.template:
    # Override Jinja control structure syntax so that it doesn't
    # cause issues with ShellCheck.
    block_end_string: '%#'
    block_start_string: '#%'
    dest: '{{ __vhost_base_directory }}/deployment.conf.sh'
    group: 'root'
    owner: '{{ deploy_to_vhost__administrator_username }}'
    mode: 0640
    src: 'deployment.conf.sh.j2'

- name: 'Make Sentry aware of deployment'
  tags:
    - 'sentry'
  block:
    - name: 'Make Sentry aware of release'
      ansible.builtin.uri:
        body: |
          {
            "projects": ["{{ deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].sentry_project }}"],
            "refs": [
              {
                "commit": "{{ __release_metadata.release_git_sha }}",
                "repository": "{{ __release_metadata.github_project }}"
              }
            ],
            "version": "{{ __release_metadata.release_timestamp }}"
          }
        body_format: 'json'
        headers:
          Authorization: 'Bearer {{ deploy_to_vhost__sentry_auth_token }}'
        method: 'POST'
        status_code: 201
        url: 'https://sentry.io/api/0/organizations/{{ deploy_to_vhost__sentry_organisation }}/releases/'

    - name: 'Make Sentry aware of deployment'
      ansible.builtin.uri:
        body: |
          {
            "environment": "{{ deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].env_vars.APP_ENV }}"
          }
        body_format: 'json'
        headers:
          Authorization: 'Bearer {{ deploy_to_vhost__sentry_auth_token }}'
        method: 'POST'
        status_code: 201
        url: 'https://sentry.io/api/0/organizations/{{ deploy_to_vhost__sentry_organisation }}/releases/{{ __release_metadata.release_timestamp }}/deploys/'
  when: deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].sentry_project is defined
  delegate_to: 'localhost'
  run_once: true

- name: 'Force all currently notified handlers to run'
  ansible.builtin.meta: 'flush_handlers'

- name: 'Perform smoke tests'
  tags:
    - 'smoketest'
  block:
    - name: 'Check release is running on host'
      ansible.builtin.command:
        # The "--resolve" option allows "/etc/hosts"-type functionality
        # without having to edit system-wide configuration files.
        # Ansible's 'uri' module has no similar functionality.
        cmd: >
          curl -IsS
          --fail
          --insecure
          --resolve '{{ deploy_to_vhost__site_domain }}:443:127.0.0.1'
          --user-agent 'deploy-to-vhost-smoke-test'
          'https://{{ deploy_to_vhost__site_domain }}'
        warn: false
      register: __smoketest_response
      changed_when: false

    - name: 'Check release is live'
      ansible.builtin.uri:
        http_agent: 'deploy-to-vhost-smoke-test'
        url: 'https://{{ deploy_to_vhost__site_domain }}/'
        url_password: '{{ deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].auth.password | default("") }}'
        url_username: '{{ deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].auth.username | default("") }}'
        validate_certs: false
      register: __smoketest_response
      failed_when: >
        (__smoketest_response.x_release_timestamp is not defined) or
        (__release_metadata.release_timestamp | string not in __smoketest_response.x_release_timestamp)
      delegate_to: 'localhost'
      run_once: true
      no_log: true
  rescue:
    # This pretty-prints any errors from the block above.
    - name: 'Pretty-print any smoketest-related errors'
      ansible.builtin.debug:
        var: __smoketest_response

- name: 'Clean up virtual host releases folder'
  ansible.builtin.shell: 'set -eo pipefail; ls -1tr {{ __vhost_base_directory }}/releases | head -n -2 | xargs rm -rf'
  args:
    chdir: '{{ __vhost_base_directory }}/releases'
    executable: '/bin/bash'
  changed_when: true

- name: 'Ensure the deployment lock file is removed'
  ansible.builtin.file:
    path: '{{ __vhost_base_directory }}/deploy.lock'
    state: 'absent'
