# The following tasks perform pre-deployment checks.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A "public" directory is required for Apache to serve files from.
- name: 'Check release archive for "public" directory'
  ansible.builtin.command:
    cmd: 'tar -tvf {{ deploy_to_vhost__release_artifact_folder }}/release.tgz "./public/"'
    warn: false
  changed_when: false
  delegate_to: 'localhost'
  run_once: true

- name: 'Check release timestamp is a non-empty string'
  ansible.builtin.assert:
    that:
      - __release_metadata.release_timestamp | length > 0

- name: 'Check release base directory does not already exist'
  block:
    - name: 'Get release base directory status'
      ansible.builtin.stat:
        path: '{{ __release_base_directory }}'
      register: __release_base_directory_status

    - name: 'Check release base directory does not already exist'
      ansible.builtin.assert:
        that: __release_base_directory_status.stat.islnk is not defined

- name: 'Check Sentry organisation is valid'
  tags:
    - 'sentry'
  ansible.builtin.uri:
    headers:
      Authorization: 'Bearer {{ deploy_to_vhost__sentry_auth_token }}'
    status_code: 200
    url: 'https://sentry.io/api/0/organizations/{{ deploy_to_vhost__sentry_organisation }}/'
  when: deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].sentry_project is defined
  delegate_to: 'localhost'
  run_once: true

# Sentry requires that a release's Git commit SHA-1 hash exists in the
# project's Git repository on GitHub before it can associate the commit
# with the release.
- name: 'Check release Git commit SHA-1 hash is valid with GitHub'
  tags:
    - 'sentry'
  ansible.builtin.uri:
    headers:
      Authorization: 'Token {{ deploy_to_vhost__github_auth_token }}'
    status_code: 200
    url: 'https://api.github.com/repos/{{ __release_metadata.github_project }}/git/commits/{{ __release_metadata.release_git_sha }}'
  when: deploy_to_vhost__vhosts[deploy_to_vhost__site_domain].sentry_project is defined
  delegate_to: 'localhost'
  run_once: true
