# The following tasks perform any necessary pre-deployment setup.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# The following directory structure is similar to the one used by
# Capistrano and similar deployment tools.
- name: 'Ensure base deployment-related directories exist'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'www-data'
    mode: 0750
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/{{ item }}'
    state: 'directory'
  loop:
    - 'releases' # holds all deployments.
    - 'shared' # holds data that persists across releases.

- name: 'Ensure "private" shared-data directory exists'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'root'
    mode: 0750
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/shared/private'
    state: 'directory'

- name: 'Ensure "protected" shared-data directory exists'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'www-data'
    # Octal file permissions must contain a leading zero or be a string.
    mode: '2750'
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/shared/protected'
    state: 'directory'

- name: 'Ensure release scheduled task helper scripts exist'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.template:
    # By default, "run-parts" ignores executable files that have
    # periods in their names.
    dest: '/etc/cron.{{ item }}/vhost-{{ deploy_to_vhost__site_domain | replace(".","-") }}'
    group: 'root'
    mode: 0755
    owner: 'root'
    src: 'vhost-cron.sh.j2'
  loop:
    - 'hourly'
    - 'daily'
    - 'weekly'
    - 'monthly'
