# The following tasks perform any necessary pre-deployment setup.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# The following directory structure is similar to the one used by
# Capistrano and similar deployment tools.
- name: 'Ensure base deployment-related directories exist'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'www-data'
    mode: 0750
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/{{ item }}'
    state: 'directory'
  loop:
    - 'releases' # holds all deployments.
    - 'shared' # holds data that persists across releases.

- name: 'Ensure "private" shared-data directory exists'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'root'
    mode: 0750
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/shared/private'
    state: 'directory'

- name: 'Ensure "protected" shared-data directory exists'
  tags:
    - 'deploy-to-vhost:setup'
  ansible.builtin.file:
    group: 'www-data'
    # Octal file permissions must contain a leading zero or be a string.
    mode: '2750'
    owner: '{{ deploy_to_vhost__administrator_username }}'
    path: '{{ __vhost_base_directory }}/shared/protected'
    state: 'directory'

- name: 'Ensure website crontab file exists'
  tags:
    - 'deploy-to-vhost:setup'
  block:
    - name: 'Ensure existing website crontab file is cleared'
      ansible.builtin.file:
        path: '/etc/cron.d/website-{{ deploy_to_vhost__site_domain | replace(".","-") }}'
        state: 'absent'

    - name: 'Ensure base website crontab file exists'
      ansible.builtin.cron:
        cron_file: 'website-{{ deploy_to_vhost__site_domain | replace(".","-") }}'
        env: true
        job: '{{ item.job }}'
        name: '{{ item.name }}'
        user: 'root'
      loop:
        - job: '{{ __vhost_base_directory }}/deployment.conf.sh'
          name: 'BASH_ENV'
        - job: '{{ deploy_to_vhost__administrator_email }}'
          name: 'MAILTO'

    - name: 'Set release crontab file name variable'
      ansible.builtin.set_fact:
        __release_crontab: 'website-{{ deploy_to_vhost__site_domain | replace(".","-") }}'
