# "ubuntu_pro" Ansible role variables.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the token for associating an Ubuntu Pro
# subscription to the host. For more information, see
# <https://ubuntu.com/pro>.
ubuntu_pro__subscription_token: '{{ undef() }}'
