# The following tasks perform APT-related maintainance tasks.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure APT package lists are up-to-date'
  ansible.builtin.apt:
    force_apt_get: true
    update-cache: true

- name: 'Perform dry-run of "apt-get dist-upgrade"'
  ansible.builtin.command: 'apt-get --simulate dist-upgrade'
  args:
    warn: false
  register: __apt_update_dry_run
  changed_when: false

- name: 'Parse dry-run "apt-get dist-upgrade" output'
  ansible.builtin.set_fact:
    __updates: '{{ __apt_update_dry_run.stdout_lines | apt_simulate_output_cleanup }}'
  changed_when: false

- name: 'Perform dry-run of "apt-get autoremove"'
  ansible.builtin.command: 'apt-get --simulate autoremove'
  args:
    warn: false
  register: __apt_removal_dry_run
  changed_when: false

- name: 'Parse dry-run "apt-get autoremove" output'
  ansible.builtin.set_fact:
    __removals: '{{ __apt_removal_dry_run.stdout_lines | apt_simulate_output_cleanup }}'
  changed_when: false

- name: 'Ensure APT packages are up-to-date'
  block:
    - name: 'Show APT packages to be updated'
      ansible.builtin.debug:
        var: __updates

    - name: 'Wait for user confirmation to proceed'
      ansible.builtin.pause:

    - name: 'Ensure APT packages are up-to-date'
      ansible.builtin.apt:
        upgrade: 'dist'
  when: __updates.0 is defined

- name: 'Ensure out-of-date and unused APT packages are removed'
  block:
    - name: 'Show APT packages to be removed'
      ansible.builtin.debug:
        var: __removals

    - name: 'Wait for user confirmation to proceed'
      ansible.builtin.pause:

    - name: 'Ensure out-of-date and unused APT packages are removed'
      ansible.builtin.apt:
        autoremove: true
  when: __removals.0 is defined
