# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: Reload Apache
  service:
    name: apache2
    state: reloaded

- name: Reload php-fpm
  service:
    name: php7.2-fpm
    state: reloaded
