# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: 'kubernetes_playground'
  become: true
  roles:
    - 'base'
    - 'docker'
    - 'kubernetes_playground'

- hosts: 'playground'
  become: true
  roles:
    - 'base'

- hosts: 'production'
  become: true
  roles:
    - 'backup'
    - 'base'
    - 'letsencrypt'
    - 'livepatch'
    - 'monitoring'
    - 'webserver'
  vars:
    webserver__vhosts_cleanup: '{{ cli__vhosts_cleanup | default(False) }}'

- hosts: 'development'
  become: true
  roles:
    - 'base'
    - 'development'
    - 'docker'
    - 'golang'
    - 'syncthing'
    - 'tailscale'
    - 'webserver'
  vars:
    webserver__vhosts_cleanup: '{{ cli__vhosts_cleanup | default(False) }}'
