# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: 'all'
  gather_facts: false
  become: true
  pre_tasks:
    - name: 'End play for non-applicable hosts'
      ansible.builtin.meta: 'end_host'
      when: deploy_website__vhosts[cli__site_domain] is not defined

    - name: 'Gather Facts'
      ansible.builtin.setup:

  roles:
    - role: 'deploy_website'
      vars:
        deploy_website__release_artifact_folder: '{{ cli__release_artifact_folder }}'
        deploy_website__site_domain: '{{ cli__site_domain }}'
