# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: 'development'
  become: true
  roles:
    - 'base'
    - 'development'
    - 'docker'
    - 'erlang_and_elixir'
    - 'golang'
    - 'nodejs'
    - 'rust'
    - 'syncthing'
    - 'tailscale'
    - 'webserver'
  vars:
    webserver__vhosts_cleanup: '{{ cli__vhosts_cleanup | default(False) }}'

# For work-related machines, we only need to provision a small subset of
# personal stuff (dotfiles, utilities, etc) as everything else is
# provisioned by other means. Go is required for a few utilities.
- hosts: 'development_work'
  become: true
  roles:
    - 'development'
    - 'golang'

- hosts: 'kubernetes_playground'
  become: true
  roles:
    - 'base'
    - 'docker'
    - 'kubernetes_playground'

- hosts: 'playground'
  become: true
  roles:
    - 'base'

- hosts: 'production'
  become: true
  roles:
    - 'backup'
    - 'base'
    - 'letsencrypt'
    - 'livepatch'
    - 'monitoring'
    - 'webserver'
  vars:
    letsencrypt__certificate_cleanup: '{{ cli__website_cleanup | default(False) }}'
    webserver__vhosts_cleanup: '{{ cli__website_cleanup | default(False) }}'
