# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: localhost
  gather_facts: no
  become: no
  vars:
    __release_timestamp: '{{ lookup("pipe", "date +%Y%m%d%H%M%S") }}'

  tasks:
    - name: Ensure project has been checked out with Git
      git:
        repo: '{{ repo }}'
        dest: ./temp
        version: '{{ version | default("HEAD") }}'
      register: git_repo

    - name: Ensure project release information file exists
      copy:
        content: |
          ---
          release_hash: {{ git_repo.after }}
          release_timestamp: {{ __release_timestamp }}
        dest: ./temp/release.yml

    - name: 'Build project release archive'
      command: '{{ cli__build_release_command | default("task release") }}'
      args:
        chdir: './temp'
        creates: './temp/release.tgz'
      changed_when: true
      environment:
        RELEASE_ID: '{{ __release_timestamp }}'

- hosts: all
  gather_facts: no
  become: yes
  vars:
    project_base_directory: '/var/www/{{ site }}'
    project_release_base_directory: '{{ project_base_directory }}/releases/{{ release_timestamp }}'
    # Accepted strings: "standard", "php", "kirby3".
    project_type: standard

  tasks:
    - name: Get applicable hosts for release
      meta: end_host
      when: sites[site] is not defined

    - name: Gather Facts
      setup:

    - name: Include variables from project release information file
      include_vars:
        dir: ./temp
        files_matching: release.yml

    - name: Ensure project release folder exists
      file:
        path: '{{ project_release_base_directory }}'
        state: directory
        owner: '{{ administrator_username }}'
        group: www-data
        mode: '0750'

    - name: Ensure project release archive has been extracted
      unarchive:
        src: ./temp/release.tgz
        dest: '{{ project_release_base_directory }}'
      become: no

    - name: 'Check for and install PHP dependencies'
      block:
        - name: 'Get status of "composer.json" in release'
          stat:
            path: '{{ project_release_base_directory }}/composer.json'
          register: __composer_json_status

        - name: 'Install PHP dependencies with Composer'
          composer:
            classmap_authoritative: true
            command: 'install'
            working_dir: '{{ project_release_base_directory }}'
          become: false
          changed_when: true
          when: __composer_json_status.stat.exists

    - name: Ensure owners and permissions for files in project release folder are correct
      command: '{{ item }}'
      args:
        chdir: '{{ project_release_base_directory }}'
      changed_when: true
      loop:
        - "find . -wholename './composer.*' -exec chown '{{ administrator_username }}:root' {} \\;"
        - "find . -wholename './private*' -exec chown '{{ administrator_username }}:root' {} \\;"
        - "find . -wholename './protected*' -exec chown '{{ administrator_username }}:www-data' {} \\;"
        - "find . -wholename './public*' -exec chown '{{ administrator_username }}:www-data' {} \\;"
        - 'find . -type d -exec chmod 0750 {} \;'
        - 'find . -type f -exec chmod 0640 {} \;'
        - "find . -type f -wholename './private/bin/*' -exec chmod 0750 {} \\;"
        - "find . -type f -wholename './private/cron/*' -exec chmod 0750 {} \\;"

    - name: Ensure Kirby-3-specific writable folders exist in project release folder
      file:
        path: '{{ project_release_base_directory }}/{{ item }}'
        state: directory
        owner: www-data
        group: www-data
        mode: '2750'
      when: project_type == 'kirby3'
      loop:
        - protected/cache
        - public/media

    - name: Ensure project release Apache configuration file exists
      copy:
        content: |
          Define DEPLOYED_RELEASE {{ release_timestamp | quote }}

          SetEnv DEPLOYED_RELEASE {{ release_timestamp | quote }}
          SetEnv DEPLOYED_RELEASE_GIT_HASH {{ release_hash | quote }}

          {% if sites[site].env_vars is defined %}
            {% for i in sites[site].env_vars | dict2items %}
              SetEnv {{ i.key }} {{ i.value | string | quote }}
            {% endfor %}
          {% endif %}
        dest: '{{ project_base_directory }}/current_release.apache2.conf'
        owner: '{{ administrator_username }}'
        group: root
        mode: '0640'

    - name: Ensure project release environment variables file exists
      copy:
        content: |
          export DEPLOYED_RELEASE={{ release_timestamp | quote }}
          export DEPLOYED_RELEASE_GIT_HASH={{ release_hash | quote }}
          export SHARED_ROOT={{ project_base_directory ~ '/shared' | quote }}
          {% if sites[site].env_vars is defined %}
            {% for i in sites[site].env_vars | dict2items %}
              export {{ i.key }}={{ i.value | string | quote }}
            {% endfor %}
          {% endif %}
        dest: '{{ project_base_directory }}/current_release.sh'
        owner: '{{ administrator_username }}'
        group: root
        mode: '0640'

    - name: Ensure Sentry is aware of project release and deployment
      block:
      - name: Ensure Sentry is aware of project release and deployment
        uri:
          url: 'https://sentry.io/api/0/organizations/{{ sentry_organisation }}/releases/'
          method: POST
          body_format: json
          headers:
            Authorization: 'Bearer {{ sentry_auth_token }}'
          body: |
            {
              "projects": ["{{ sites[site].sentry_project }}"],
              "refs": [
                {
                  "commit": "{{ release_hash }}",
                  "repository": "{{ sites[site].github_project }}"
                }
              ],
              "version": "{{ release_timestamp }}"
            }
          status_code: 201

      - name: Ensure Sentry is aware of project release deployment
        uri:
          url: 'https://sentry.io/api/0/organizations/{{ sentry_organisation }}/releases/{{ release_timestamp }}/deploys/'
          method: POST
          body_format: json
          headers:
            Authorization: 'Bearer {{ sentry_auth_token }}'
          body: |
            {
              "environment": "{{ sites[site].env_vars.APP_ENV  }}",
            }
          status_code: 201
      when: sites[site].sentry_project is defined
      run_once: true
      delegate_to: localhost

    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Reload PHP-FPM
      service:
        name: php7.4-fpm
        state: reloaded

    - name: Ensure only current and previous project release folders exist
      shell: 'set -eo pipefail; ls -1tr /var/www/{{ site }}/releases | head -n -2 | xargs rm -rf'
      args:
        chdir: '{{ project_base_directory }}/releases'
        executable: /bin/bash
      changed_when: true

    - name: 'Perform smoke tests'
      tags:
        - 'smoketest'
      block:
        - name: 'Check release deployments'
          uri:
            headers:
              Host: '{{ site }}'
            url: 'https://localhost/'
            url_password: '{{ sites[site].auth.password | default("") }}'
            url_username: '{{ sites[site].auth.username | default("") }}'
            validate_certs: false
          register: __smoketest_response
          failed_when: >
            (__smoketest_response.x_release is not defined) or
            (release_timestamp | string not in __smoketest_response.x_release)
      rescue:
        # This pretty-prints any errors from the block above.
        - debug:
            var: __smoketest_response

- hosts: localhost
  become: no
  tasks:
    - name: Ensure temporary build folder no longer exists
      file:
        path: ./temp
        state: absent
