# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Perform package maintenance'
  hosts: 'all'
  become: true
  gather_facts: false
  serial: 1
  roles:
    - 'apt_maintainance'
