# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: 'kubernetes_playground'
  become: true
  roles:
    - 'base'
    - 'docker'
    - 'kubernetes-playground'

- hosts: 'production'
  become: true
  roles:
    - 'backup'
    - 'base'
    - 'letsencrypt'
    - 'livepatch'
    - 'monitoring'
    - 'webserver'

- hosts: 'development'
  become: true
  roles:
    - 'base'
    - 'development'
    - 'docker'
    - 'webserver'

- hosts: 'macos'
  become: true
  roles:
    - 'macos'
