# The following playbook removes unused Apache virtual hosts.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- hosts: 'all'
  become: true
  roles:
    - role: 'webserver'
      vars:
        webserver__vhosts_cleanup: true
