# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Provision development machines'
  hosts: 'development'
  become: true
  roles:
    - 'base'
    - 'chrome'
    - 'composer'
    - 'development'
    - 'docker'
    - 'erlang_and_elixir'
    - 'golang'
    - 'imagemagick'
    - 'nodejs'
    - 'python'
    - 'rust'
    - 'syncthing'
    - 'tailscale'
    - 'virtualbox'
    - 'webserver'
  vars:
    webserver__vhosts_cleanup: '{{ cli__website_cleanup | default(False) }}'

# Work-related machines are provisioned by other means, so only run what
# is necessary for things like dotfiles, miscellaneous utilities, etc.
- name: 'Provision work-related machines'
  hosts: 'development_work'
  become: true
  roles:
    - 'development'
    - 'golang'
    - 'python'

- name: 'Provision testing and experimentation machines'
  hosts: 'playground_production'
  become: true
  roles:
    - 'backup'
    - 'base'
    - 'imagemagick'
    - 'lego'
    - 'monitoring'
    - 'webserver'
  vars:
    webserver__vhosts_cleanup: '{{ cli__website_cleanup | default(False) }}'

- name: 'Provision servers for hosting websites'
  hosts: 'production'
  become: true
  roles:
    - 'backup'
    - 'base'
    - 'imagemagick'
    - 'lego'
    - 'livepatch'
    - 'monitoring'
    - 'webserver'
  vars:
    certbot__certificate_cleanup: '{{ cli__website_cleanup | default(False) }}'
    webserver__vhosts_cleanup: '{{ cli__website_cleanup | default(False) }}'
