---
# Damien Dart's Ansible Playbook
#
# This playbook is used to provision the server I host some simple
# websites on and my development environments.
#
#   - This playbook has been tested on Ubuntu 18.04.
#   - For Ubuntu 18.04 machines, Ansible needs to be told to use Python
#     3 (by setting "ansible_python_interpreter").
#   - This playbook works with the Mitogen plugin. For more information,
#     see <https://mitogen.readthedocs.io/en/stable/ansible.html>.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

- hosts: production
  become: yes
  roles:
    - backup
    - base
    - letsencrypt
    - livepatch
    - monitoring
    - webserver

- hosts: local
  become: yes
  roles:
    - base
    - development
    - webserver
