# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
version: '3'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  dependencies:
    cmds:
      - 'pip3 install -r requirements.txt'
    desc: 'Install Python dependencies'

  lint:
    cmds:
      - task: 'lint:ansible'
      - task: 'lint:packer'
      - task: 'lint:python'
      - task: 'lint:shell'
      - task: 'lint:yaml'
    desc: 'Run all linting-related tasks'

  lint:ansible:
    cmds:
      - 'ansible-lint -p --nocolor playbook-deploy-website.yml'
      - 'ansible-lint -p --nocolor playbook-package-maintainance.yml'
      - 'ansible-lint -p --nocolor playbook-provision.yml'
    desc: 'Lint Ansible-related files with Ansible Lint'

  lint:packer:
    cmds:
      - 'packer validate packer/*.hcl'
    desc: 'Lint Packer templates with Packer'

  lint:python:
    cmds:
      - 'flake8 roles/*/*/*.py* tests/*.py'
    desc: 'Lint Python scripts with Flake8'

  lint:shell:
    cmds:
      - 'shellcheck roles/*/*/*.sh*'
    desc: 'Lint shell scripts with ShellCheck'

  lint:yaml:
    cmds:
      - 'yamllint -s -f parsable . .github'
    desc: 'Lint YAML files with yamllint'
