---
version: 2

output: prefixed

tasks:
  default:
    deps:
      - task: lint

  dependencies:
    cmds:
      - pip3 install -r requirements.txt
    desc: Install Python dependencies

  lint:
    cmds:
      - yamllint -s -f parsable .
      - ansible-lint -p --nocolor provision.yml
    desc: Run a bunch of linting stuff
