# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
version: '3'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  dependencies:
    cmds:
      - task: 'dependencies:packer'
      - task: 'dependencies:python'
    desc: 'Install project dependencies'

  dependencies:python:
    cmds:
      - '.venv/bin/python -m pip install -r requirements.txt'
    desc: 'Install Python dependencies'

  dependencies:packer:
    cmds:
      - 'packer init misc/packer/*.hcl'
    desc: 'Install Packer plugin binaries'

  lint:
    cmds:
      - task: 'lint:ansible'
      - task: 'lint:packer'
      - task: 'lint:python'
      - task: 'lint:shell'
      - task: 'lint:yaml'
    desc: 'Run all linting-related tasks'

  lint:ansible:
    cmds:
      - cmd: '.venv/bin/ansible-lint -p --nocolor playbook-deploy-website.yml'
      - cmd: '.venv/bin/ansible-lint -p --nocolor playbook-package-maintainance.yml'
      - cmd: '.venv/bin/ansible-lint -p --nocolor playbook-provision.yml'
    desc: 'Lint Ansible-related files with Ansible Lint'

  lint:packer:
    cmds:
      - 'packer validate misc/packer/*.hcl'
    desc: 'Lint Packer templates with Packer'

  lint:python:
    cmds:
      - task: 'lint:python:black'
      - task: 'lint:python:flake8'
    desc: 'Run all Python-linting tasks'

  lint:python:black:
    cmds:
      - '.venv/bin/black --check --diff roles/*/*/*.py tests/*.py'
    desc: 'Lint Python scripts with Black'

  lint:python:flake8:
    cmds:
      - '.venv/bin/flake8 roles/*/*/*.py* tests/*.py'
    desc: 'Lint Python scripts with Flake8'

  lint:shell:
    cmds:
      - 'shellcheck roles/*/*/*.sh*'
    desc: 'Lint shell scripts with ShellCheck'

  lint:yaml:
    cmds:
      - '.venv/bin/yamllint -s -f parsable . .github'
    desc: 'Lint YAML files with yamllint'

  start:
    cmds:
      - 'python3.13 -m venv .venv'
    desc: 'Create a Python virtual environment for development, running Ansible, and testing'
