# "rust" Ansible role variables.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a checksum used to verify the integrity of the
# "rustup-init" binary. Checksums are available at
# <https://rust-lang.github.io/rustup/installation/other.html>. See also
# "rust__rustup_init_url".
rust__rustup_init_checksum: 'sha256:0b2f6c8f85a3d02fde2efc0ced4657869d73fccfce59defb4e8d29233116e6db'

# A string containing the URL to the "rustup-init" binary.
rust__rustup_init_url: 'https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string specifying the username of the account whose home directory
# will have Rust and friends installed into.
rust__user_username: '{{ undef() }}'
