# Required variables for the "tailscale" role.
#
# Commented-out variables must be defined elsewhere (in an inventory,
# playbook, or at runtime).
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a Tailscale auth key. To create and manage auth
# keys, see <https://login.tailscale.com/admin/settings/keys>.
# tailscale__auth_key: ''
