# "development" Ansible role variables.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
development__binary_archives:
  # See <https://github.com/junegunn/fzf/releases>.
  - binaries: 'fzf'
    checksum: 'sha256:8fd0e0b93bdf64ba90081ffb6658d77ea5a024c122b36852b1de30f9d2733754'
    url: 'https://github.com/junegunn/fzf/releases/download/v0.70.0/fzf-0.70.0-linux_amd64.tar.gz'

  # See <https://developer.hashicorp.com/packer/downloads>.
  - binaries: 'packer'
    checksum: 'sha256:648d704bec73805a5508ed612185a9e5858ca7d57b730b88b1a54c3af3a91f5f'
    url: 'https://releases.hashicorp.com/packer/1.15.1/packer_1.15.1_linux_amd64.zip'

  # See <https://github.com/koalaman/shellcheck/releases>.
  - checksum: 'sha256:8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198'
    # Ansible gets funny about trying to extract individual files from
    # "tar.xz" archives using the "include" parameter. A pretty naff
    # workaround is to awkwardly recreate the "include" functionality
    # with "extra_opts".
    extra_opts:
      - '--exclude=LICENSE.txt'
      - '--exclude=README.txt'
      - '--transform'
      - 's/^shellcheck-v0.11.0\///'
    url: 'https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.linux.x86_64.tar.xz'

development__debian_packages:
  # See <https://github.com/jgm/pandoc/releases>.
  - checksum: 'sha256:ce4ac48f48aa7eadc1f5dbdf3449a1739f188ecb8c5421c5adc070fe7479e567'
    url: 'https://github.com/jgm/pandoc/releases/download/3.9.0.2/pandoc-3.9.0.2-1-amd64.deb'

  # See <https://github.com/BurntSushi/ripgrep/releases>.
  - checksum: 'sha256:62ce186675c71edbc7c48a67dc36f986974551354d6ce63726adc2d85aad802c'
    url: 'https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep_15.1.0-1_amd64.deb'

  # See <https://github.com/go-task/task/releases>.
  - checksum: 'sha256:1a9a3d52d7b8a482d950f7ee26beebd1217c8f0924db306855dcd91e286f46e8'
    url: 'https://github.com/go-task/task/releases/download/v3.49.1/task_3.49.1_linux_amd64.deb'

    # See <https://github.com/StackExchange/dnscontrol/releases>.
  - checksum: 'sha256:f4883c766dfd10c1f5bae5c0dfa77ef497174503502a1fc9599ecd4ac53c5cf1'
    url: 'https://github.com/StackExchange/dnscontrol/releases/download/v4.36.1/dnscontrol-4.36.1.amd64.deb'

# The following checksum is for the entr 5.8 source code archive
# "5.8.tar.gz" from <https://github.com/eradman/entr/tags>.
development__entr_source_archive_checksum: 'sha256:dc9a2bdc556b2be900c1d8cdf432de26492de5af3ffade000d4bfd97f3122bfb'
development__entr_version: '5.8'

# The following checksum is for "PkgTTC-Iosevka-34.3.0.zip" from
# <https://github.com/be5invis/Iosevka/releases>.
development__iosevka_archive_checksum: 'sha256:bf5a4f83c4a01511d03b07f091ad4896dc27dc359d978e13ab2976488fa423c2'
development__iosevka_version: '34.3.0'

# Obsidian releases are available at <https://obsidian.md/download> and
# <https://github.com/obsidianmd/obsidian-releases/releases/>. The
# following checksum is for the file "obsidian_1.12.7_amd64.deb".
development__obsidian_package_checksum: 'sha256:3644e3ef19bcd23db4d17f7c73311b5245429391a2a48b361da93375f59712b0'
development__obsidian_version: '1.12.7'

development__projects_folder: 'Shed'
development__run_gui_tasks: false
development__update_dotfiles: false
development__use_dotfiles_https_url: false


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
development__download_cache_directory: '{{ undef() }}'

# A string containing the Pushover application key to be used by the
# "po" utility script from the "toolbox" Git repository.
development__po_application_key: '{{ unset() }}'
#
# A string containing the Pushover user key to be used by the "po"
# utility script from the "toolbox" Git repository.
development__po_user_key: '{{ unset() }}'
