# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure all Docker-related files are present'
  ansible.builtin.copy:
    dest: '{{ home_server__docker_directory }}'
    group: 'users'
    owner: '{{ home_server__user_username }}'
    src: '{{ role_path }}/files/docker/'
