# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Restart OpenSSH Server'
  service:
    name: 'ssh'
    state: 'restarted'

- name: 'Restart UFW'
  service:
    name: 'ufw'
    state: 'restarted'
