# This role installs and configures Tarsnap to perform daily backups.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the Tarsnap package signing key is present for APT'
  ansible.builtin.apt_key:
    state: 'present'
    url: 'https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc'

- name: 'Ensure the Tarsnap repository is present in APT sources list'
  ansible.builtin.apt_repository:
    repo: 'deb http://pkg.tarsnap.com/deb/{{ ansible_distribution_release }} ./'
    state: 'present'

- name: 'Ensure Tarsnap is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name: 'tarsnap'
    state: 'present'

# We use a key with reduced permissions to prevent any intruders from
# deleting any existing archives, however they would still be able to
# stop any future backups or add new archives with faulty data. A
# write-only key can be created with "tarsnap-keymgmt". For more
# information, see <https://www.tarsnap.com/tips.html#write-only-keys>.
- name: 'Ensure a write-only Tarsnap key is present'
  ansible.builtin.copy:
    content: '{{ backup__tarsnap_write_only_key }}'
    dest: '/root/tarsnap.key'
    group: 'root'
    mode: 0600
    owner: 'root'

- name: 'Ensure Tarsnap is set up to run daily'
  ansible.builtin.template:
    dest: '/etc/cron.daily/tarsnap'
    group: 'root'
    mode: 0755
    src: 'tarsnap-cron.sh.j2'
    owner: 'root'
