# "nodejs" Ansible role variables.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a checksum used to verify the integrity of the
# Node.js binary archive "node-v22.19.0-linux-x64.tar.xz". See also
# "nodejs__version". Node.js binary archives and checksums are
# available at <https://nodejs.org/en/download>.
nodejs__nodejs_archive_checksum: 'sha256:c0649af18e6a24f6fe5535a3e86b341dd49a8e71117c8b68bde973ef834f16f2'

# A string containing the version of Node.js to install.
nodejs__nodejs_version: '22.19.0'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
nodejs__download_cache_directory: '{{ undef() }}'
