# Default and required variables for the "nodejs" role.
#
# Commented-out variables must be defined elsewhere (in an inventory,
# playbook, or at runtime).
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a checksum used to verify the integrity the
# Node.js binary archive download. For valid checksum formats, see
# <https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-checksum>.
nodejs__archive_checksum: 'sha256:9429e26d9a35cb079897f0a22622fe89ff597976259a8fcb38b7d08b154789dc'

# A string containing the version of Node.js to install.
nodejs__version: '18.12.0'


# A string containing the directory where Node.js binary archives are
# stored to prevent unnecessary downloading when tasks are rerun.
# nodejs__download_cache_directory: ''
