# Default and required variables for the "nodejs" role.
#
# Commented-out variables must be defined elsewhere (in an inventory,
# playbook, or at runtime).
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a checksum used to verify the integrity the
# Node.js binary archive "node-v18.12.1-linux-x64.tar.xz".
nodejs__archive_checksum: 'sha256:4481a34bf32ddb9a9ff9540338539401320e8c3628af39929b4211ea3552a19e'

# A string containing the version of Node.js to install.
nodejs__version: '18.12.1'


# A string containing the directory where Node.js binary archives are
# stored to prevent unnecessary downloading when tasks are rerun.
# nodejs__download_cache_directory: ''
