# This role installs and configures my macOS stuff.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure required packages are installed'
  homebrew:
    name:
      - 'fzf'
      - 'go-task/tap/go-task'
      - 'node@{{ macos__node_major_version }}'
      - 'php@{{ macos__php_version }}'
      - 'shellcheck'
      - 'tig'
      - 'tree'
      - 'vim'
    state: 'present'
  become: false

- name: 'Ensure the BrowserStack Local binary is installed'
  unarchive:
    dest: '/usr/local/bin'
    group: 'admin'
    mode: 0755
    owner: '{{ macos__user_username }}'
    remote_src: true
    src: 'https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip'

- name: 'Ensure the Packer binary is installed'
  unarchive:
    dest: '/usr/local/bin'
    group: 'admin'
    mode: 0755
    owner: '{{ macos__user_username }}'
    remote_src: true
    src: 'https://releases.hashicorp.com/packer/{{ macos__packer_version }}/packer_{{ macos__packer_version }}_darwin_amd64.zip'

- name: 'Ensure custom ".zshrc" exists in administrator home directory'
  template:
    dest: '/Users/{{ macos__user_username }}/.zshrc'
    group: 'staff'
    mode: 0600
    owner: '{{ macos__user_username }}'
    src: 'zshrc.sh.j2'
