---
- name: Ensure monitoring-related packages are installed
  apt:
    force_apt_get: yes
    name:
      - fail2ban
      - logrotate
      - logwatch
      - monit
      - msmtp-mta
    state: present

- name: Ensure custom notfication scripts exist
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0700'
  with_items:
    - { src: session-notify.sh.j2, dest: /usr/local/bin/session-notify }

- name: Ensure SSH session notifications are enabled
  pamd:
    name: sshd
    new_control: optional
    new_module_path: pam_exec.so
    new_type: session
    module_arguments: /usr/local/bin/session-notify
    state: after
    type: session
    module_path: pam_mail.so
    control: optional

- name: Ensure custom msmtp configuration file exist
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: '0600'

- name: Ensure custom Fail2ban configuration file exist
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0600'
  notify: Restart Fail2ban

- name: Ensure custom Logwatch configuration file exist
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: '0600'

- name: Ensure custom Monit configuration file exist
  template:
    src: monitrc.j2
    # The weird name is to ensure this configuration file is loaded last.
    dest: /etc/monit/conf.d/zzz.conf
    owner: root
    group: root
    mode: '0600'
    validate: monit -c %s -t
  notify: Restart Monit

- name: Ensure custom Tarsnap logrotate configuration file exists (if required)
  template:
    src: tarsnap-cron-logrotate.j2
    dest: /etc/logrotate.d/tarsnap-cron
    owner: root
    group: root
    mode: '0600'
  when: '"backup" in ansible_play_role_names'

- name: Ensure monitoring-related services are operational and set to run on boot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - fail2ban
    - monit
