# Installs and configurates monitoring-related stuff.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# Store verified downloaded files to prevent unnecessary redownloading.
- name: 'Ensure download cache directory exists'
  ansible.builtin.file:
    path: '{{ monitoring__download_cache_directory }}'
    group: 'root'
    mode: '0777'
    owner: 'root'
    state: 'directory'

- name: 'Ensure monitoring-related packages are installed'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - 'fail2ban'
      - 'logrotate'
      - 'logwatch'
      - 'monit'
    state: 'present'

- name: 'Ensure custom notfication scripts exist'
  ansible.builtin.template:
    dest: '{{ item.dest }}'
    group: 'root'
    mode: '0700'
    owner: 'root'
    src: '{{ item.src }}'
  loop:
    - dest: '/usr/local/bin/session-notify'
      src: 'session-notify.sh.j2'

- name: 'Ensure SSH session notifications are enabled'
  community.general.pamd:
    control: 'optional'
    module_arguments: '/usr/local/bin/session-notify'
    module_path: 'pam_mail.so'
    name: 'sshd'
    new_control: 'optional'
    new_module_path: 'pam_exec.so'
    new_type: 'session'
    state: 'after'
    type: 'session'

- name: 'Ensure custom Fail2ban configuration file exist'
  ansible.builtin.template:
    dest: '/etc/fail2ban/jail.local'
    group: 'root'
    owner: 'root'
    mode: '0600'
    src: 'jail.local.j2'
  notify: 'Restart Fail2ban'

- name: 'Ensure custom Logwatch configuration file exist'
  ansible.builtin.template:
    dest: '/etc/logwatch/conf/logwatch.conf'
    group: 'root'
    mode: '0600'
    owner: 'root'
    src: 'logwatch.conf.j2'

- name: 'Ensure custom Monit configuration file exist'
  ansible.builtin.template:
    # The weird name is to ensure this configuration file is loaded last.
    dest: '/etc/monit/conf.d/zzz.conf'
    group: 'root'
    mode: '0600'
    owner: 'root'
    src: 'monitrc.j2'
    validate: 'monit -c %s -t'
  notify: 'Restart Monit'

- name: 'Ensure custom Logwatch logrotate configuration file exists'
  ansible.builtin.template:
    dest: '/etc/logrotate.d/logwatch'
    group: 'root'
    mode: '0644'
    owner: 'root'
    src: 'logrotate-logwatch.conf.j2'

- name: 'Ensure Fail2ban and Monit services are operational and set to run on boot'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  loop:
    - 'fail2ban'
    - 'monit'

- name: 'Include Tarsnap monitoring installation and configuration tasks'
  ansible.builtin.include_tasks: 'backup.yml'

- name: 'Include Prometheus Node Exporter installation and configuration tasks'
  ansible.builtin.include_tasks: 'node-exporter.yml'
