# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the Tailscale package signing key is present for APT'
  ansible.builtin.apt_key:
    state: 'present'
    url: 'https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg'

- name: 'Ensure the Tailscale repository is present in APT sources list'
  ansible.builtin.apt_repository:
    # The following repository details are from
    # <https://pkgs.tailscale.com/stable/ubuntu/focal.list>.
    repo: 'deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main'
    state: 'present'

- name: 'Ensure Tailscale is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name: 'tailscale'
    state: 'present'

- name: 'Ensure Tailscale is running and set to start on system boot'
  ansible.builtin.service:
    enabled: true
    name: 'tailscaled'
    state: 'started'

- name: 'Get Tailscale connection status'
  ansible.builtin.shell:
    cmd: 'tailscale status || /bin/true'
  changed_when: false
  register: __tailscale_status

- name: 'Ensure the host is connected to Tailscale'
  ansible.builtin.command: 'tailscale up --authkey={{ tailscale__auth_key }}'
  changed_when: __tailscale_up.rc == 0
  notify: 'Notify user to check host Tailscale connection status'
  register: __tailscale_up
  when: "'Logged out' in __tailscale_status.stdout or 'NoState' in __tailscale_status.stdout"
