# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# The following repository details are from
# <https://pkgs.tailscale.com/stable/ubuntu/>.
- name: 'Ensure the Tailscale repository is present in APT sources list'
  ansible.builtin.deb822_repository:
    components:
      - 'main'
    enabled: true
    name: 'Tailscale'
    signed_by: 'https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg'
    suites:
      - '{{ ansible_distribution_release }}'
    state: 'present'
    types:
      - 'deb'
    uris: 'https://pkgs.tailscale.com/stable/ubuntu'
  register: __tailscale_repository

- name: 'Ensure Tailscale is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name: 'tailscale'
    state: 'present'
    update_cache: '{{ __tailscale_repository is changed }}'

- name: 'Ensure Tailscale is running and set to start on system boot'
  ansible.builtin.service:
    enabled: true
    name: 'tailscaled'
    state: 'started'

- name: 'Get Tailscale connection status'
  ansible.builtin.shell:
    cmd: 'tailscale status || /bin/true'
  changed_when: false
  register: __tailscale_status

- name: 'Ensure the host is connected to Tailscale'
  ansible.builtin.command: 'tailscale up --authkey={{ tailscale__auth_key }}'
  changed_when: __tailscale_up.rc == 0
  notify: 'Notify user to check host Tailscale connection status'
  register: __tailscale_up
  when: "'Logged out' in __tailscale_status.stdout or 'NoState' in __tailscale_status.stdout"
