# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the Tarsnap repository is present in APT sources list'
  ansible.builtin.deb822_repository:
    enabled: true
    name: 'Tarsnap'
    signed_by: 'https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc'
    suites:
      - './'
    state: 'present'
    types:
      - 'deb'
    uris: 'https://pkg.tarsnap.com/deb/{{ ansible_distribution_release }}'
  register: __tarsnap_repository

- name: 'Ensure Tarsnap is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name: 'tarsnap'
    state: 'present'
    update_cache: '{{ __tarsnap_repository is changed }}'

- name: 'Ensure Tarsnap is set up to back up things'
  when: tarsnap__directories_to_backup | length > 0
  block:
    - name: 'Ensure a write-only Tarsnap key is present'
      ansible.builtin.copy:
        content: '{{ tarsnap__tarsnap_write_only_key }}'
        dest: '/root/tarsnap.key'
        group: 'root'
        mode: 0600
        owner: 'root'

    - name: 'Ensure Tarsnap is set up to run daily'
      ansible.builtin.template:
        dest: '/etc/cron.daily/tarsnap'
        group: 'root'
        mode: 0755
        src: 'tarsnap-cron.sh.j2'
        owner: 'root'
