# Cleans up any certificate detritus.
#
# There is some gnarly Jinja filter usage here, so as a precaution
# changes will only be made when the "certbot__certificate_cleanup"
# variable is set to a truthy value; that way you can use the dry-run to
# review what gets deleted.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Get Certbot certificates status'
  ansible.builtin.command: 'certbot certificates'
  register: __certbot_certificates
  changed_when: false
  ignore_errors: true

- name: "Ensure old and unused certificates no longer exist{{ ' (DRY RUN)' if not (certbot__certificate_cleanup | default(False)) }}"
  ansible.builtin.command: 'certbot delete --cert-name {{ item }}'
  when: certbot__certificate_cleanup | default(False)
  loop: >
    {{
      __certbot_certificates.stdout_lines
        | select('match', '^\s+Certificate Name:')
        | map('regex_replace', '^\s+Certificate Name:\s+')
        | difference(certbot__certificates.keys())
      | default([])
    }}
