# The following tasks install Docker.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the Docker package signing key is present for APT'
  apt_key:
    state: 'present'
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- name: 'Ensure the Docker repository is present in APT sources list'
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: 'present'

- name: 'Ensure Docker is installed'
  apt:
    force_apt_get: true
    name:
      # The following packages are as per the installation guide at
      # <https://docs.docker.com/engine/install/ubuntu/#install-docker-engine>.
      - 'containerd.io'
      - 'docker-ce'
      - 'docker-ce-cli'
    state: 'present'

- name: 'Ensure administrator can run docker commands without sudo'
  user:
    name: '{{ development__user_username }}'
    groups: 'docker'
    append: true
  notify: 'Notify user about group membership update'
