# Installs dotfiles-related stuff.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

- name: 'Run dotfiles-related tasks'
  become: true
  become_user: '{{ development__user_username }}'
  # See the comment below about SSH agent forwarding for why the
  # "ignore-errors" rule check is suppressed.
  ignore_errors: true # noqa: ignore-errors
  block:
    - name: 'Ensure a key for "github.com" exists in administrator known hosts list'
      ansible.builtin.known_hosts:
        key: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' # noqa 204
        name: 'github.com'

    # The following task will fail if using SSH agent forwarding when
    # connecting to a host; tasks that use "become" and friends do not
    # inherit any environment variables set by SSH during login,
    # including the "SSH_AUTH_SOCK" environment variable required for
    # SSH agent forwarding. For more information and potential
    # workarounds, see <https://stackoverflow.com/q/24124140>.
    - name: 'Ensure the "snippets" and "toolbox" Git repositories exists'
      ansible.builtin.git:
        dest: '/home/{{ development__user_username }}/{{ development__projects_folder }}/{{ item }}'
        repo: 'git@github.com:damiendart/{{ item }}.git'
        update: false
        version: 'master'
      loop:
        - 'snippets'
        - 'toolbox'

    - name: 'Ensure the "toolbox" install script runs successfully'
      ansible.builtin.command: '/home/{{ development__user_username }}/{{ development__projects_folder }}/toolbox/install'
      register: toolbox_install
      changed_when: toolbox_install.stdout is search('Created')
