# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

- name: 'Run tasks to install and set up dotfiles'
  become: true
  become_user: '{{ development__user_username }}'
  block:
    - name: 'Ensure keys for GitHub hosts exists in administrator known hosts list'
      ansible.builtin.known_hosts:
        key: '{{ item }}'
        name: 'github.com'
      loop:
        # Keys for verifying GitHub hosts are documented at
        # <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints>.
        - 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl'
        - 'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg='
        - 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk='

    # The following task will fail if using SSH agent forwarding when
    # connecting to a host; tasks that use "become" and friends do not
    # inherit any environment variables set by SSH during login,
    # including the "SSH_AUTH_SOCK" environment variable required for
    # SSH agent forwarding. For more information and potential
    # workarounds, see <https://stackoverflow.com/q/24124140>.
    - name: 'Ensure the "toolbox" Git repository exists'
      ansible.builtin.git:
        dest: '/home/{{ development__user_username }}/{{ development__projects_folder }}/toolbox'
        repo: 'git@github.com:damiendart/toolbox.git'
        update: '{{ development__update_dotfiles }}'
        version: 'master'

    - name: 'Ensure the "toolbox" install script runs successfully'
      ansible.builtin.command: '/home/{{ development__user_username }}/{{ development__projects_folder }}/toolbox/install'
      register: toolbox_install
      changed_when: toolbox_install.stdout is search("✔")

    - name: 'Ensure a valid configuration file for the "po" utility script exists'
      ansible.builtin.template:
        dest: '/home/{{ development__user_username }}/.config/toolbox/po.ini'
        mode: '0600'
        src: 'po.ini.j2'
