# The following tasks install Go via binary archive.
#
#   - If Go has been previously installed using a different method (e.g.
#     a package manager), the following tasks will not delete that
#     version and will need to be removed manually.
#   - The following tasks will install Go in "/usr/local/go". You may
#     need to update your PATH environment variable to include
#     "/usr/local/go/bin" after running these tasks.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Check for an existing installation of Go'
  block:
    - name: 'Get the version of Go currently installed (if available)'
      ansible.builtin.set_fact:
        __go_version: "{{ lookup('file', '/usr/local/go/VERSION') }}"
  rescue:
    - name: 'Set Go version variable to an empty string'
      ansible.builtin.set_fact:
        __go_version: ''

- name: 'Ensure Go is installed'
  block:
    - name: 'Ensure existing Go installation is removed'
      ansible.builtin.file:
        path: '/usr/local/go'
        state: 'absent'

    - name: 'Ensure Go is installed'
      ansible.builtin.unarchive:
        dest: '/usr/local'
        group: 'root'
        owner: 'root'
        remote_src: true
        src: 'https://golang.org/dl/go{{ development__go_version }}.linux-amd64.tar.gz'
  when: development__go_version not in __go_version

- name: 'Ensure Go-related tools are installed'
  ansible.builtin.command: '/usr/local/go/bin/go install {{ item }}'
  become: true
  become_user: '{{ development__user_username }}'
  # There currently isn't a nice way of determining if "go install"
  # has changed anything; the redundant "changed_when" conditional is
  # there to appease Ansible Lint.
  changed_when: true
  loop: '{{ development__go_installable_packages }}'
