# Installs and configures GUI-related stuff.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# "psutil" is required by the "community.general.dconf" Ansible module.
- name: 'Ensure the "psutil" Python package is installed for system Python'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - 'python3-psutil'
    state: 'present'

- name: 'Ensure custom Gnome settings have been applied'
  community.general.dconf:
    state: 'present'
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  become: true
  become_user: '{{ development__user_username }}'
  loop:
    - key: '/org/gnome/desktop/interface/enable-animations'
      value: 'false'
    - key: '/org/gnome/mutter/center-new-windows'
      value: 'true'
    - key: '/org/gnome/shell/extensions/desktop-icons/show-home'
      value: 'false'
    - key: '/org/gnome/shell/extensions/desktop-icons/show-trash'
      value: 'false'

# I use "xsel" for general clipboard wrangling (mainly out of habit),
# but reach for "xclip" when dealing with slightly more elaborate data
# formats (e.g. copying HTML from Firefox).
- name: 'Ensure "xclip" and "xsel" are installed'
  ansible.builtin.apt:
    name:
      - 'xclip'
      - 'xsel'
    state: 'present'

- name: 'Ensure fonts directory exists in administrator home directory'
  ansible.builtin.file:
    group: '{{ development__user_username }}'
    mode: 0700
    owner: '{{ development__user_username }}'
    path: '/home/{{ development__user_username }}/.fonts'
    state: 'directory'

- name: 'Ensure the Iosevka TTC archive is downloaded'
  ansible.builtin.get_url:
    checksum: '{{ development__iosevka_archive_checksum }}'
    dest: '{{ development__download_cache_directory }}/PkgTTC-Iosevka-{{ development__iosevka_version }}.zip'
    group: 'root'
    mode: 0755
    owner: 'root'
    url: 'https://github.com/be5invis/Iosevka/releases/download/v{{ development__iosevka_version }}/PkgTTC-Iosevka-{{ development__iosevka_version }}.zip'

- name: 'Ensure Iosevka TTC files are installed'
  ansible.builtin.unarchive:
    dest: '/home/{{ development__user_username }}/.fonts'
    group: '{{ development__user_username }}'
    owner: '{{ development__user_username }}'
    src: '{{ development__download_cache_directory }}/PkgTTC-Iosevka-{{ development__iosevka_version }}.zip'

# I've found that Gnome Terminal does not get along with the Super TTC
# version of Iosevka. Using individual TTC files is the easiest remedy.
- name: 'Ensure any old Iosevka Super TTC files are removed'
  ansible.builtin.file:
    path: '/home/{{ development__user_username }}/.fonts/iosevka.ttc'
    state: 'absent'

- name: 'Ensure the Obsidian Debian package is downloaded'
  ansible.builtin.get_url:
    checksum: '{{ development__obsidian_package_checksum }}'
    dest: '{{ development__download_cache_directory }}/obsidian-{{ development__obsidian_version }}-amd64.deb'
    group: 'root'
    mode: 0755
    owner: 'root'
    url: 'https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ development__obsidian_version }}/obsidian_{{ development__obsidian_version }}_amd64.deb'

- name: 'Ensure Obsidian is installed'
  ansible.builtin.apt:
    deb: '{{ development__download_cache_directory }}/obsidian-{{ development__obsidian_version }}-amd64.deb'
    state: 'present'

# Account for a bug where Obsidian's Debian package for v0.12.15 creates
# an incorrect symbolic link in "/usr/bin".
- name: 'Ensure a symbolic link to Obsidian exists in "/usr/bin"'
  ansible.builtin.file:
    dest: '/usr/bin/obsidian'
    group: 'root'
    owner: 'root'
    src: '/opt/Obsidian/obsidian'
    state: 'link'
