# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: Ensure the NodeSource package signing key is present for APT
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Ensure NodeSource repository is present in APT sources list
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    state: present

- name: Ensure development-related packages are installed
  apt:
    force_apt_get: yes
    name:
      - build-essential
      - nodejs
      - python3-pip
      - shellcheck
      - tig
      - tree
      - vim
    state: present

- name: Ensure the Task snap is installed
  snap:
    classic: yes
    name: task
    state: present

- name: Ensure development-related Python packages are installed in administrator home directory
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
    executable: /usr/bin/pip3
    extra_args: --user
  become: yes
  become_user: "{{ administrator_username }}"

- name: Ensure fzf executable is installed
  unarchive:
    src: "https://github.com/junegunn/fzf-bin/releases/download/{{ fzf_version }}/fzf-{{ fzf_version }}-linux_amd64.tgz"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
    remote_src: yes

- name: Ensure fzf supplimentary files exist
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - dest: /usr/local/etc/fzf-completion.bash
      url: "https://raw.githubusercontent.com/junegunn/fzf/{{ fzf_version }}/shell/completion.bash"
    - dest: /usr/local/etc/fzf-key-bindings.bash
      url: "https://raw.githubusercontent.com/junegunn/fzf/{{ fzf_version }}/shell/key-bindings.bash"

- name: 'Ensure custom ".bash_aliases" exists in administrator home directory'
  template:
    src: bash_aliases.sh.j2
    dest: "/home/{{ administrator_username }}/.bash_aliases"
    owner: "{{ administrator_username }}"
    group: "{{ administrator_username }}"
    mode: '0600'

- name: Run GUI-based development tasks
  block:
  - name: Ensure fonts directory exists in administrator home directory
    file:
      path: /home/{{ administrator_username }}/.fonts/iosevka
      state: directory
      owner: "{{ administrator_username }}"
      group: "{{ administrator_username }}"
      mode: '0700'

  - name: Ensure Iosevka TrueType font files are present in admin home directory
    unarchive:
      src: "https://github.com/be5invis/Iosevka/releases/download/{{ development__iosevka_version }}/{{ development__iosevka_archive_filename }}"
      dest: "/home/{{ administrator_username }}/.fonts/iosevka"
      remote_src: yes
      owner: "{{ administrator_username }}"
      group: "{{ administrator_username }}"
      exclude: "{{ development__iosevka_archive_excludes }}"

  - name: Ensure the PhpStorm snap is installed
    snap:
      classic: yes
      name: phpstorm
      state: present
  tags:
    - gui

- include: 'virtualbox.yml'
