---
- name: Ensure the NodeSource package signing key is present for APT
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Ensure NodeSource repository is present in APT sources list
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    state: present

- name: Ensure development-related packages are installed
  apt:
    force_apt_get: yes
    name:
      - build-essential
      - nodejs
      - python-pip
      - python3-pip
      - ruby
      - ruby-dev
      - shellcheck
      - tig
      - tree
    state: present

- name: Ensure the Task snap is installed
  snap:
    classic: yes
    name: task
    state: present

- name: Ensure development-related Python packages are installed in administrator home directory
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
    executable: /usr/bin/pip3
    extra_args: --user
  become: yes
  become_user: "{{ administrator_username }}"

- name: 'Ensure custom ".bash_profile" exists in administrator home directory'
  template:
    src: bash_profile.sh.j2
    dest: "/home/{{ administrator_username }}/.bash_profile"
    owner: "{{ administrator_username }}"
    group: "{{ administrator_username }}"
    mode: "0644"
