# This role installs and configures my development-specific stuff.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the NodeSource package signing key is present for APT'
  apt_key:
    state: 'present'
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

- name: 'Ensure NodeSource repository is present in APT sources list'
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ development__node_major_version }}.x {{ ansible_distribution_release }} main'
    state: 'present'

- name: 'Ensure development-related packages are installed'
  apt:
    force_apt_get: true
    name:
      - 'build-essential'
      - 'nodejs'
      - 'python3-pip'
      - 'shellcheck'
      - 'tig'
      - 'tree'
      - 'vim'
    state: 'present'

- name: 'Ensure Task is installed'
  snap:
    classic: true
    name: 'task'
    state: 'present'

- name: 'Ensure development-related Python packages are installed in administrator home directory'
  pip:
    executable: '/usr/bin/pip3'
    extra_args: '--user'
    name:
      - 'virtualenv'
      - 'virtualenvwrapper'
  become: true
  become_user: '{{ development__user_username }}'

- name: 'Ensure fzf is installed'
  unarchive:
    dest: '/usr/local/bin'
    group: 'root'
    mode: 0755
    owner: 'root'
    remote_src: true
    src: 'https://github.com/junegunn/fzf-bin/releases/download/{{ development__fzf_version }}/fzf-{{ development__fzf_version }}-linux_amd64.tgz'

- name: 'Ensure fzf supplimentary files are installed'
  get_url:
    dest: '/usr/local/etc/fzf-{{ item }}'
    group: 'root'
    mode: 0755
    owner: 'root'
    url: 'https://raw.githubusercontent.com/junegunn/fzf/{{ development__fzf_version }}/shell/{{ item }}'
  loop:
    - 'completion.bash'
    - 'key-bindings.bash'

- name: 'Ensure custom ".bash_aliases" exists in administrator home directory'
  template:
    dest: '/home/{{ development__user_username }}/.bash_aliases'
    group: '{{ development__user_username }}'
    mode: 0600
    owner: '{{ development__user_username }}'
    src: 'bash_aliases.sh.j2'

- name: 'Run GUI-based development tasks'
  block:
  - name: 'Ensure fonts directory exists in administrator home directory'
    file:
      group: '{{ development__user_username }}'
      mode: 0700
      owner: '{{ development__user_username }}'
      path: '/home/{{ development__user_username }}/.fonts/iosevka'
      state: 'directory'

  - name: 'Ensure the Iosevka font files are installed'
    unarchive:
      dest: '/home/{{ administrator_username }}/.fonts/iosevka'
      exclude: '{{ development__iosevka_archive_excludes }}'
      group: '{{ development__user_username }}'
      owner: '{{ development__user_username }}'
      remote_src: true
      src: 'https://github.com/be5invis/Iosevka/releases/download/{{ development__iosevka_version }}/{{ development__iosevka_archive_filename }}'

  - name: 'Ensure the PhpStorm snap is installed'
    snap:
      classic: true
      name: 'phpstorm'
      state: 'present'
  tags:
    - 'gui'

- include: 'docker.yml'
- include: 'virtualbox.yml'
- include: 'open-vm-tools.yml'
