# The following tasks install Node via binary archive.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Get status of currently-installed Node'
  ansible.builtin.stat:
    path: '/usr/local/node/bin/node'
  changed_when: false
  register: __node_binary

- name: 'Get version of currently-installed Node'
  ansible.builtin.command: '/usr/local/node/bin/node --version'
  changed_when: false
  failed_when: false
  register: __node_version
  when: __node_binary.stat.exists

- name: 'Ensure Node is installed'
  block:
    - name: 'Ensure existing Node installation is removed'
      ansible.builtin.file:
        path: '/usr/local/node'
        state: 'absent'

    - name: 'Ensure base Node directory is present'
      ansible.builtin.file:
        group: 'root'
        mode: '0755'
        owner: 'root'
        path: '/usr/local/node'
        state: 'directory'

    - name: 'Ensure Node is installed'
      ansible.builtin.unarchive:
        dest: '/usr/local/node'
        extra_opts:
          - '--strip-components=1'
        group: 'root'
        owner: 'root'
        remote_src: true
        src: 'https://nodejs.org/dist/v{{ development__node_version }}/node-v{{ development__node_version }}-linux-x64.tar.xz'
  when: development__node_version not in (__node_version.stdout | default('') | trim)
