# Installs Open Virtual Machine Tools, if required.
#
# The Open Virtual Machine Tools is an open-source implementation of
# VMware Tools. For more information, please see
# <https://kb.vmware.com/s/article/2073803>.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Get virtualisation status'
  ansible.builtin.command: 'dmidecode -s system-product-name'
  register: system_product_name
  changed_when: false

- name: 'Ensure Open Virtual Machine Tools is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name: 'open-vm-tools'
    state: 'present'
  when: system_product_name.stdout == 'VMware Virtual Platform'
