# Installs VirtualBox.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Run VirtualBox-related tasks'
  tags:
    - 'virtualbox'
  when: development__run_virtualbox_tasks | bool
  block:
    - name: 'Ensure the VirtualBox package signing key is present for APT'
      ansible.builtin.apt_key:
        state: 'present'
        url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'

    - name: 'Ensure the VirtualBox repository is present in APT sources list'
      ansible.builtin.apt_repository:
        repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
        state: 'present'

    - name: 'Ensure VirtualBox is installed'
      ansible.builtin.apt:
        force_apt_get: true
        name: 'virtualbox-{{ development__virtualbox_version }}'
        state: 'present'

    # To access USB devices from VirtualBox guests, the host user must
    # be a member of the "vboxusers" group. For more information, see
    # <https://www.virtualbox.org/manual/ch02.html#install-linux-vboxusers>.
    - name: 'Ensure administrator user has access to USB devices in VirtualBox'
      ansible.builtin.user:
        name: '{{ development__user_username }}'
        groups: 'vboxusers'
        append: true
      notify: 'Notify user about "vboxusers" group membership update'
