# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---

# Polypane releases are available at
# <https://github.com/firstversionist/polypane/releases/>.
polypane__polypane_package_checksum: 'sha256:f8cb89bf0797f0f1435e4121431996520991541b4269d67c0a0c3947641dd416'
polypane__polypane_version: '29.0.0'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
polypane__download_cache_directory: '{{ undef() }}'
