# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---

# VueScan releases are available at
# <https://www.hamrick.com/alternate-versions.html>.

vuescan__vuescan_package_checksum: 'sha256:de44ffb2d8610ae8f1e6e5271222df0b31e3c1a1a39003fd993cd95b673c7842'
vuescan__vuescan_version: '9.8.53'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
vuescan__download_cache_directory: '{{ undef() }}'
