# "python" Ansible role variables.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# A string containing a checksum used to verify the integrity the
# Python binary archive download. See also "python__archive_url" and
# "python__version". Python binary archives and checksums are available
# at <https://github.com/indygreg/python-build-standalone/releases>.
python__python_archive_checksum: 'sha256:cf84edbd74f926072cefc4300f35dd4521e3421c3128b8fd391b2d2a789b495c'

# A string containing the URL to the binary archive.
python__python_archive_url: 'https://github.com/indygreg/python-build-standalone/releases/download/20240726/cpython-3.11.9+20240726-x86_64_v3-unknown-linux-gnu-install_only.tar.gz'

# A string containing the version of Python to install.
python__python_version: '3.11.9'


# The following variables will have host-specific and/or sensitive
# values and must be defined elsewhere (in an inventory, playbook, at
# runtime, etc).

# A string containing the directory where downloaded files are stored to
# prevent unnecessary downloading when tasks are rerun.
python__download_cache_directory: '{{ undef() }}'
