# The following role installs Erlang and Elixir.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure old Erlang Solutions package signing key is not present for APT'
  ansible.builtin.apt_key:
    state: 'absent'
    url: 'https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc'

- name: 'Ensure old Erlang Solutions repository entry is not present in APT sources list'
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release }} contrib'
    state: 'absent'

- name: 'Ensure Erlang Solutions repository is present in APT sources list'
  ansible.builtin.deb822_repository:
    components:
      - 'contrib'
    enabled: true
    name: 'Erlang Solutions'
    signed_by: 'https://packages.erlang-solutions.com/{{ ansible_distribution | lower }}/erlang_solutions.asc'
    suites:
      - '{{ ansible_distribution_release | lower }}'
    state: 'present'
    types:
      - 'deb'
    uris: 'https://packages.erlang-solutions.com/{{ ansible_distribution | lower }}'

- name: 'Ensure Erlang and Elixir packages are installed'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - 'elixir'
      # Installing the Elixir package alone does not install everything
      # required to run Pheonix applications. For more information,
      # see <https://stackoverflow.com/q/36512519>.
      - 'erlang'
    state: 'present'
