# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
webserver__add_vhosts_to_etc_hosts: false
webserver__composer_version: '1.10.1'
webserver__composer_sha256: '1831f266580f221189dc04d4b58d7fc50c934ffc3a0eca89ecb4a53aa44867e2'
webserver__install_xdebug: false
webserver__php_version: 7.4
webserver__static_caching: true
