# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
# admin_email_address: example@example.com
# admin_username: example
# composer_github_token: 1234567890
# server_name: www.example.com
# sites:
#  www.example.com:
#    aliases:
#      - this.is.optional
#    auth:
#      password: this_is_optional
#      username: this_is_optional
#    env_vars:
#      FOO: BAR
webserver_static_caching: true
composer_version: 1.9.1
composer_sha256_hash: 1f210b9037fcf82670d75892dfc44400f13fe9ada7af9e787f93e50e3b764111
php_version: 7.4
