# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
webserver__add_vhosts_to_etc_hosts: false
webserver__composer_version: 1.9.1
webserver__composer_sha256: 1f210b9037fcf82670d75892dfc44400f13fe9ada7af9e787f93e50e3b764111
webserver__install_xdebug: false
webserver__php_version: 7.4
webserver__static_caching: true
