# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
networks:
  forgejo:
    external: false

services:
  forgejo:
    environment:
      - 'FORGEJO__MAILER__FROM=${FORGEJO__MAILER__FROM:?err}'
      - 'FORGEJO__MAILER__PASSWD=${FORGEJO__MAILER__PASSWD:?err}'
      - 'FORGEJO__MAILER__SMTP_ADDR=${FORGEJO__MAILER__SMTP_ADDR:?err}'
      - 'FORGEJO__MAILER__USER=${FORGEJO__MAILER__USER:?err}'
      - 'FORGEJO__SECURITY__INTERNAL_TOKEN=${FORGEJO__SECURITY__INTERNAL_TOKEN:?err}'
      - 'FORGEJO__SECURITY__SECRET_KEY=${FORGEJO__SECURITY__SECRET_KEY:?err}'
      - 'USER_GID=${FORGEJO_USER_GID:?err}'
      - 'USER_UID=${FORGEJO_USER_UID:?err}'
    container_name: 'forgejo'
    hostname: 'diskstation'
    image: 'codeberg.org/forgejo/forgejo:12'
    networks:
      - 'forgejo'
    ports:
      - '3000:3000'
      - '222:22'
    restart: 'unless-stopped'
    volumes:
      - '${FORGEJO_DIRECTORY:?err}:/data'
      - './forgejo/app.ini:/data/gitea/conf/app.ini'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/TZ:/etc/timezone:ro'

  syncthing:
    image: 'syncthing/syncthing'
    container_name: 'syncthing'
    hostname: 'diskstation'
    environment:
      - 'PGID=${SYNCTHING_PGID:?err}'
      - 'PUID=${SYNCTHING_PUID:?err}'
      - 'TZ=Europe/London'
    volumes:
      - '${SYNCTHING_DIRECTORY:?err}:/var/syncthing'
    ports:
      - '8384:8384'
      - '22000:22000/tcp'
      - '22000:22000/udp'
    restart: 'unless-stopped'
