# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Notify user to check host Tailscale connection status'
  ansible.builtin.debug:
    msg: >-
      Please check the connection status of this host on Tailscale's
      admin panel (<https://login.tailscale.com/admin/machines>).
