# The following role installs Docker and friends.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure kernel modules for containerd are loaded'
  community.general.modprobe:
    name: '{{ item }}'
    state: 'present'
  loop:
    - 'br_netfilter'
    - 'overlay'

# IP forwarding is required so that the Linux kernel can route traffic
# from hosted containers to the outside world.
- name: 'Ensure IP forwarding is enabled'
  ansible.posix.sysctl:
    name: 'net.ipv4.ip_forward'
    state: 'present'
    value: '1'

# These settings are required so that the Linux kernel can perform
# address translation in packets going to and from hosted containers.
- name: 'Ensure "iptables" can see bridged traffic'
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    state: 'present'
    value: '{{ item.value }}'
  loop:
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }

- name: 'Ensure the Docker repository is present in APT sources list'
  ansible.builtin.deb822_repository:
    components:
      - 'stable'
    enabled: true
    name: 'Docker'
    signed_by: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    suites:
      - '{{ ansible_distribution_release | lower }}'
    state: 'present'
    types:
      - 'deb'
    uris: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}'
  register: __docker_repository

- name: 'Ensure Docker and containerd are installed'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      # The following packages are as per the installation guide at
      # <https://docs.docker.com/engine/install/ubuntu/#install-docker-engine>.
      - 'containerd.io'
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'docker-buildx-plugin'
      - 'docker-compose-plugin'
    state: 'present'
    update_cache: '{{ __docker_repository is changed }}'

- name: 'Ensure administrator can run docker commands without sudo'
  ansible.builtin.user:
    name: '{{ docker__administrator_user_username }}'
    groups: 'docker'
    append: true
  notify: 'Notify user about group membership update'

- name: 'Get containerd default configuration'
  ansible.builtin.command: 'containerd config default'
  changed_when: false
  register: __containerd_config_default

- name: 'Ensure containerd configuration file contains default configuration'
  ansible.builtin.copy:
    content: '{{ __containerd_config_default.stdout }}'
    dest: '/etc/containerd/config.toml'
    group: 'root'
    mode: 0600
    owner: 'root'
  notify: 'Restart containerd'

- name: 'Ensure containerd and Docker are running and start on system boot'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  loop:
    - 'containerd'
    - 'docker'
