# Installs and configures bits-and-pieces for a base Ubuntu environment.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the timezone is set correctly'
  community.general.timezone:
    name: 'Europe/London'

- name: 'Ensure an non-root administrator user account exists'
  ansible.builtin.user:
    append: true
    generate_ssh_key: '{{ base__administrator_account_ssh_key }}'
    groups:
      - 'sudo'
    name: '{{ base__administrator_account_username }}'
    password: '{{ base__administrator_account_password | password_hash("sha512") }}'
    ssh_key_type: '{{ base__administrator_account_ssh_key_type }}'
    state: 'present'
    update_password: 'on_create'
  register: __user
  no_log: true

- name: 'Prompt user to check SSH-public-key-related bits-and-pieces'
  when: __user.ssh_public_key is defined
  block:
    - name: 'Show SSH public key for non-root administrator user'
      ansible.builtin.debug:
        var: __user.ssh_public_key

    - name: 'Prompt user to check SSH public key'
      ansible.builtin.debug:
        msg: >-
          Ensure any applicable Ansible inventories and GitHub accounts
          contain the SSH public key shown above

    - name: 'Wait for user confirmation to proceed'
      ansible.builtin.pause:

- name: 'Ensure non-root administrator user has authorised SSH keys'
  ansible.posix.authorized_key:
    exclusive: true
    user: '{{ base__administrator_account_username }}'
    key: '{{ base__administrator_account_authorised_keys }}'
    state: 'present'

- name: 'Ensure base software is installed'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - 'curl'
      - 'git'
      - 'htop'
      - 'msmtp-mta'
      # Ansible requires Passlib for certain functions.
      - 'python3-passlib'
      - 'openssh-server'
      - 'ufw'
      - 'unzip'
    state: 'present'

- name: 'Ensure OpenSSH Server and UFW are running and start on system boot'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  loop:
    - 'ssh'
    - 'ufw'

- name: 'Ensure the OpenSSH Server UFW profile is active'
  community.general.ufw:
    name: 'OpenSSH'
    rule: 'limit'
  notify: 'Restart UFW'

- name: 'Ensure security-related OpenSSH Server options are configured'
  ansible.builtin.lineinfile:
    dest: '/etc/ssh/sshd_config'
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
    state: 'present'
  loop:
    - line: 'MaxAuthTries 3'
      regexp: '^MaxAuthTries'
    - line: 'PasswordAuthentication no'
      regexp: '^PasswordAuthentication'
    - line: 'PermitRootLogin no'
      regexp: '^PermitRootLogin'
    - line: 'X11Forwarding no'
      regexp: '^X11Forwarding'
  notify: 'Restart OpenSSH Server'

- name: 'Ensure custom msmtp configuration files exist'
  ansible.builtin.template:
    dest: '/etc/{{ item }}'
    group: 'root'
    # The msmtp configuration files has relaxed permissions as a few
    # places remain where non-root users require msmtp.
    mode: 0644
    owner: 'root'
    src: '{{ item }}.j2'
  loop:
    - 'msmtprc'
    - 'msmtp.aliases'

- name: "Ensure cron \"MAILTO\" variable is set to the non-root administrator's email address"
  ansible.builtin.cron:
    env: true
    job: '{{ base__administrator_account_email }}'
    name: 'MAILTO'
