# This role installs and configures the base environment.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the timezone is set correctly'
  timezone:
    name: 'Europe/London'

- name: 'Ensure an non-root administrator user account exists'
  user:
    append: true
    groups:
      - 'sudo'
    name: '{{ base__administrator_username }}'
    password: '{{ base__administrator_password | password_hash("sha512") }}'
    state: 'present'
    update_password: 'on_create'

- name: 'Ensure non-root administrator user has authorised SSH keys'
  authorized_key:
    exclusive: true
    user: '{{ base__administrator_username }}'
    key: '{{ base__authorised_keys }}'
    state: 'present'

- name: 'Ensure base software is installed'
  apt:
    force_apt_get: true
    name:
      - 'git'
      - 'msmtp-mta'
      # Ansible requires Passlib for certain functions.
      - 'python3-passlib'
      - 'openssh-server'
      - 'ufw'
    state: 'present'

- name: 'Ensure OpenSSH Server and UFW are running and start on system boot'
  service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  loop:
    - 'ssh'
    - 'ufw'

- name: 'Ensure the OpenSSH Server UFW profile is active'
  ufw:
    name: 'OpenSSH'
    rule: 'limit'
  notify: 'Restart UFW'

- name: 'Ensure security-related OpenSSH Server options are configured'
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    line: '{{ item }} no'
    regexp: '^{{ item }}'
    state: 'present'
  loop:
    - 'PasswordAuthentication'
    - 'PermitRootLogin'
  notify: 'Restart OpenSSH Server'

- name: 'Ensure msmtp is configured'
  template:
    dest: '/etc/msmtprc'
    group: 'root'
    # The msmtp configuration file has relaxed permissions as a few
    # places remain where non-root users require msmtp.
    mode: 0644
    owner: 'root'
    src: 'msmtprc.j2'
