# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: Ensure timezone is set correctly
  timezone:
    name: Europe/London

- name: Ensure administrator user account exists
  user:
    append: yes
    name: "{{ administrator_username }}"
    password: "{{ administrator_password }}"
    update_password: on_create
    groups:
      - sudo

- name: Ensure base packages are installed
  apt:
    force_apt_get: yes
    name:
      - git
      - msmtp-mta
      # Ansible requires Passlib for certain functions.
      - python3-passlib
      - openssh-server
    state: present

- name: Ensure ufw is configured
  ufw:
    name: "{{ item.profile }}"
    rule: "{{ item.rule }}"
    state: enabled
  notify: Restart ufw
  with_items:
    - profile: Apache Full
      rule: allow
    - profile: OpenSSH
      rule: limit

- name: Ensure OpenSSH Server doesn't allow passwords or root access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item }}"
    line: "{{ item }} no"
    state: present
  with_items:
    - PasswordAuthentication
    - PermitRootLogin
  notify: Restart OpenSSH Server

- name: Ensure administrator user account SSH keys exist
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "https://github.com/{{ administrator_github_username }}.keys"

- name: Ensure custom msmtp configuration file exist
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    # The msmtp configuration file has relaxed permissions as there
    # remain a few places where non-root users require msmtp.
    mode: '0644'
