# The following tasks performs basic Apache and PHP-FPM configuration.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure required Apache modules are enabled'
  community.general.apache2_module:
    name: '{{ item }}'
    state: 'present'
  loop:
    - 'cgid'
    - 'expires'
    - 'headers'
    - 'http2'
    - 'macro'
    - 'mpm_event'
    - 'proxy_fcgi'
    - 'proxy_http'
    - 'rewrite'
    - 'setenvif'
    - 'status'
    - 'socache_shmcb'
    - 'ssl'
  notify: 'Reload Apache'

- name: 'Ensure legacy and unnecessary Apache modules are disabled'
  community.general.apache2_module:
    force: true
    name: '{{ item }}'
    state: 'absent'
  loop:
    - 'autoindex'
    - 'dav'
    - 'include'
    - 'mpm_prefork'
  notify: 'Reload Apache'

- name: 'Ensure legacy or unnecessary Apache configuration files are disabled'
  ansible.builtin.command: 'a2disconf {{ item }}'
  args:
    removes: '/etc/apache2/conf-enabled/{{ item }}.conf'
  loop:
    - 'charset'
    - 'localized-error-pages'
    - 'other-vhosts-access-log'
    - 'serve-cgi-bin'
  notify: 'Reload Apache'

# Enabling "mod_status" brings along an unwanted configuration file
# that's hard to override elsewhere, hence the nuclear option.
- name: 'Ensure unwanted base "mod_status" Apache configuration file is removed'
  ansible.builtin.file:
    path: '/etc/apache2/mods-enabled/status.conf'
    state: 'absent'
  notify: 'Reload Apache'

- name: 'Ensure custom PHP-FPM Apache configuration file exists'
  ansible.builtin.template:
    dest: '/etc/apache2/conf-available/php{{ webserver__php_version }}-fpm.conf'
    group: 'root'
    mode: 0600
    owner: 'root'
    src: 'php-fpm.apache.conf.j2'
  notify: 'Reload Apache'

- name: 'Ensure custom Apache configuration file exists'
  ansible.builtin.template:
    dest: '/etc/apache2/conf-available/zzz.conf'
    group: 'root'
    mode: 0600
    owner: 'root'
    src: 'apache2.conf.j2'
  notify: 'Reload Apache'

- name: 'Ensure custom Apache macros configuration file exists'
  ansible.builtin.template:
    dest: '/etc/apache2/conf-available/zzz-macros.conf'
    group: 'root'
    mode: 0600
    owner: 'root'
    src: 'apache2-macros.conf.j2'
  notify: 'Reload Apache'

- name: 'Ensure custom Apache configuration files are active'
  ansible.builtin.command: 'a2enconf {{ item }}'
  args:
    creates: '/etc/apache2/conf-enabled/{{ item }}.conf'
  loop:
    - 'php{{ webserver__php_version }}-fpm'
    - 'zzz'
    - 'zzz-macros'
  notify: 'Reload Apache'

- name: 'Ensure the PHP-FPM Apache configuration file is active'
  ansible.builtin.command: 'a2enconf php{{ webserver__php_version }}-fpm'
  args:
    creates: '/etc/apache2/conf-enabled/php{{ webserver__php_version }}-fpm.conf'
  notify:
    - 'Reload Apache'
    - 'Reload PHP-FPM'

- name: 'Ensure custom PHP configuration file for PHP-FPM exists'
  ansible.builtin.template:
    dest: '/etc/php/{{ webserver__php_version }}/fpm/conf.d/99-custom.ini'
    group: 'root'
    mode: 0644
    owner: 'root'
    src: '99-custom.ini.j2'
  notify: 'Reload PHP-FPM'

- name: 'Ensure custom PHP-FPM pool configuration file exists and is active'
  ansible.builtin.template:
    dest: '/etc/php/{{ webserver__php_version }}/fpm/pool.d/zzz.conf'
    group: 'root'
    mode: 0600
    owner: 'root'
    src: 'php-fpm-pool.conf.j2'
  notify: 'Reload PHP-FPM'

- name: 'Ensure Node Exporter password file exists (if required)'
  community.general.htpasswd:
    group: 'www-data'
    mode: 0640
    name: '{{ webserver__status_path_node_exporter_username }}'
    owner: 'root'
    password: '{{ webserver__status_path_node_exporter_password }}'
    path: '/etc/apache2/node-exporter.htpasswd'
  when: webserver__status_path_node_exporter is defined
  notify: 'Reload Apache'
  no_log: true
