# Performs basic Apache and PHP-FPM configuration.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure required Apache modules are enabled'
  community.general.apache2_module:
    name: '{{ item }}'
    state: 'present'
  loop:
    - 'brotli'
    - 'cgid'
    - 'deflate'
    - 'expires'
    - 'headers'
    - 'http2'
    - 'macro'
    - 'mpm_event'
    - 'proxy_fcgi'
    - 'proxy_http'
    - 'rewrite'
    - 'setenvif'
    - 'status'
    - 'socache_shmcb'
    - 'ssl'
  notify: 'Reload Apache'

- name: 'Ensure legacy and unnecessary Apache modules are disabled'
  community.general.apache2_module:
    force: true
    name: '{{ item }}'
    state: 'absent'
  loop:
    - 'autoindex'
    - 'dav'
    - 'include'
    - 'mpm_prefork'
  notify: 'Reload Apache'

- name: 'Get all PHP-related Apache configuration files'
  ansible.builtin.find:
    paths: '/etc/apache2/conf-available'
    patterns: 'php*-fpm.conf'
  register: __php_conf_files

- name: 'Ensure legacy or unnecessary Apache configuration files are disabled'
  ansible.builtin.command: 'a2disconf {{ item }}'
  args:
    removes: '/etc/apache2/conf-enabled/{{ item }}'
  with_items:
    - 'charset.conf'
    - 'localized-error-pages.conf'
    - 'other-vhosts-access-log.conf'
    # As an Ansible host can potentially have multiple versions of PHP
    # installed, PHP should be enabled on a per-virtual-host basis. See
    # the accompanying "deploy_website" Ansible role for an example.
    - "{{ __php_conf_files.files | map(attribute='path') | map('basename') }}"
    - 'serve-cgi-bin.conf'
  notify: 'Reload Apache'

# Enabling "mod_status" brings along an unwanted configuration file
# that's hard to override elsewhere, while "mod_deflate" configuration
# is handled elsewhere.
- name: 'Ensure unwanted base Apache configuration files are disabled'
  ansible.builtin.file:
    path: '/etc/apache2/mods-enabled/{{ item }}.conf'
    state: 'absent'
  notify: 'Reload Apache'
  loop:
    - 'status'
    - 'deflate'

- name: 'Ensure custom Apache configuration file exists'
  ansible.builtin.template:
    dest: '/etc/apache2/conf-available/zzz.conf'
    group: 'root'
    mode: '0600'
    owner: 'root'
    src: 'apache2.conf.j2'
  notify: 'Reload Apache'

- name: 'Ensure custom Apache configuration files are active'
  ansible.builtin.command: 'a2enconf {{ item }}'
  args:
    creates: '/etc/apache2/conf-enabled/{{ item }}.conf'
  loop:
    - 'zzz'
  notify: 'Reload Apache'

- name: 'Ensure custom PHP-FPM configuration files exists'
  ansible.builtin.template:
    dest: '/etc/php/{{ item }}/fpm/conf.d/99-custom.ini'
    group: 'root'
    mode: '0644'
    owner: 'root'
    src: '99-custom.ini.j2'
  loop: '{{ webserver__php_versions }}'
  notify: 'Reload PHP-FPM'

- name: 'Ensure custom PHP-FPM pool configuration file exists and is active'
  ansible.builtin.template:
    dest: '/etc/php/{{ item }}/fpm/pool.d/zzz.conf'
    group: 'root'
    mode: '0600'
    owner: 'root'
    src: 'php-fpm-pool.conf.j2'
  loop: '{{ webserver__php_versions }}'
  notify: 'Reload PHP-FPM'

- name: 'Ensure Node Exporter password file exists'
  community.general.htpasswd:
    group: 'www-data'
    mode: '0640'
    name: '{{ webserver__status_path_node_exporter_username }}'
    owner: 'root'
    password: '{{ webserver__status_path_node_exporter_password }}'
    path: '/etc/apache2/node-exporter.htpasswd'
  when: webserver__status_path_node_exporter is defined
  notify: 'Reload Apache'
  no_log: true
