# The following tasks installs and configures Composer.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure the Composer executable exists'
  ansible.builtin.get_url:
    checksum: 'sha256:{{ webserver__composer_sha256 }}'
    dest: '/usr/local/bin/composer'
    group: 'root'
    mode: 0755
    owner: 'root'
    url: 'https://getcomposer.org/download/{{ webserver__composer_version }}/composer.phar'

- name: 'Ensure a Composer configuration folder for administrator exists'
  ansible.builtin.file:
    group: '{{ webserver__administrator_username }}'
    mode: 0755
    owner: '{{ webserver__administrator_username }}'
    path: '/home/{{ webserver__administrator_username }}/.config/composer'
    state: 'directory'

- name: 'Ensure the Composer "auth.json" for administrator exists'
  ansible.builtin.copy:
    content: |
      {
        "bitbucket-oauth": {},
        "github-oauth": {
          "github.com": "{{ webserver__composer_github_token }}"
        },
        "gitlab-oauth": {},
        "gitlab-token": {},
        "http-basic": {}
      }
    dest: '/home/{{ webserver__administrator_username }}/.config/composer/auth.json'
    group: '{{ webserver__administrator_username }}'
    mode: 0644
    owner: '{{ webserver__administrator_username }}'
