# This roles installs and configures Apache and friends.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure "deb.sury.org" repositories are present in APT source lists'
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/{{ item }}'
    state: 'present'
  loop:
    - 'apache2'
    - 'php'

- name: 'Ensure webserver-related packages are installed'
  ansible.builtin.apt:
    force_apt_get: true
    #   - The "libfcgi0ldbl" package provides "cgi-fcgi", a command-line
    #     tool that, amongst other things, will allow getting PHP-FPM
    #     status from the command line. For more information, see
    #     <https://maxchadwick.xyz/blog/getting-the-php-fpm-status-from-the-command-line>.
    #   - As of PHP 8.0.0, the JSON extension is a core PHP extension
    #     and doesn't require installing a separate package.
    name: >
      {{
        ['apache2', 'libfcgi0ldbl', 'goaccess']
        + webserver__php_versions
          | product(webserver__php_default_packages + webserver__php_packages_extra)
          | map('join', '-')
          | map('regex_replace', '^', 'php')
          | reject('match', 'php8..-json')
      }}
    state: 'present'

- name: 'Ensure Apache and PHP-FPM are running and start on system boot'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  with_items:
    - 'apache2'
    - "{{ webserver__php_versions | map('regex_replace', '^(.*)$', 'php\\1-fpm') }}"

# The Apache package from "deb.sury.org" does not provide an UFW profile
# out-of-the-box; the following is taken from a fresh Ubuntu install.
- name: 'Ensure an Apache UFW profile exists'
  ansible.builtin.copy:
    content: |
      [Apache Full]
      title=Web Server (HTTP,HTTPS)
      description=The Apache web server.
      ports=80,443/tcp
    dest: '/etc/ufw/applications.d/apache2-utils.ufw.profile'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'Restart UFW'

- name: 'Ensure the Apache UFW profile is active'
  community.general.ufw:
    name: 'Apache Full'
    rule: 'allow'
  notify: 'Restart UFW'

- name: 'Ensure the default PHP executable is set'
  community.general.alternatives:
    name: 'php'
    path: '/usr/bin/php{{ webserver__php_default_version }}'

- name: 'Include basic Apache and PHP-FPM configuration tasks'
  ansible.builtin.include_tasks: 'base-configure.yml'

- name: 'Include Apache virtual host configuration tasks'
  ansible.builtin.include_tasks: 'vhosts.yml'

- name: 'Include tasks to clean up old and unused virtual-host-related stuff'
  ansible.builtin.include_tasks: 'vhosts-cleanup.yml'

- name: 'Include Composer installation and configuration tasks'
  ansible.builtin.include_tasks: 'composer.yml'

- name: 'Include XDebug installation and configuration tasks'
  ansible.builtin.include_tasks: 'xdebug.yml'

# We force any notified handlers to run in case there are any changes
# that need to be applied before other roles that have this role as a
# dependency are executed.
- name: 'Force all currently notified handlers to run'
  ansible.builtin.meta: 'flush_handlers'
