# This roles installs and configures Apache and friends.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure "deb.sury.org" repositories are present in APT source lists'
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/{{ item }}'
    state: 'present'
  loop:
    - 'apache2'
    - 'php'

- name: 'Ensure webserver-related packages are installed'
  ansible.builtin.apt:
    force_apt_get: true
    name:
      - 'apache2'
      # Some PHP applications use the ImageMagick command-line tools
      # instead of the native Imagick PHP extension.
      - 'imagemagick'
      - 'goaccess'
      - 'php{{ webserver__php_version }}-cli'
      - 'php{{ webserver__php_version }}-common'
      - 'php{{ webserver__php_version }}-curl'
      - 'php{{ webserver__php_version }}-fpm'
      - 'php{{ webserver__php_version }}-gd'
      - 'php{{ webserver__php_version }}-json'
      - 'php{{ webserver__php_version }}-mbstring'
      - 'php{{ webserver__php_version }}-opcache'
      - 'php{{ webserver__php_version }}-readline'
      - 'php{{ webserver__php_version }}-xml'
      - 'php{{ webserver__php_version }}-zip'
    state: 'present'
  notify:
    - 'Reload Apache'
    - 'Reload PHP-FPM'

- name: 'Ensure Apache and PHP-FPM are running and start on system boot'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
    state: 'started'
  loop:
    - 'apache2'
    - 'php{{ webserver__php_version }}-fpm'

# The Apache package from "deb.sury.org" does not provide an UFW profile
# out-of-the-box; the following is taken from a fresh Ubuntu install.
- name: 'Ensure an Apache UFW profile exists'
  ansible.builtin.copy:
    content: |
      [Apache Full]
      title=Web Server (HTTP,HTTPS)
      description=The Apache web server.
      ports=80,443/tcp
    dest: '/etc/ufw/applications.d/apache2-utils.ufw.profile'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'Restart UFW'

- name: 'Ensure the Apache UFW profile is active'
  community.general.ufw:
    name: 'Apache Full'
    rule: 'allow'
  notify: 'Restart UFW'

- include: 'base-configure.yml'
- include: 'vhosts.yml'
- include: 'composer.yml'
- include: 'xdebug.yml'

# We force any notified handlers to run in case there are any changes
# that need to be applied before other roles that have this role as a
# dependency are executed.
- name: 'Force all currently notified handlers to run'
  ansible.builtin.meta: 'flush_handlers'
