# Installs and configures Xdebug.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Run Xdebug-related tasks'
  block:
  - name: 'Ensure Xdebug is installed'
    ansible.builtin.apt:
      force_apt_get: true
      name: "{{ webserver__xdebug_versions | map('regex_replace', '^(.*)$', 'php\\1-xdebug') }}"
      state: 'present'

  - name: 'Ensure custom Xdebug configuration file for PHP-FPM exists'
    ansible.builtin.template:
      dest: '/etc/php/{{ item }}/fpm/conf.d/99-xdebug.ini'
      group: 'root'
      mode: 0644
      owner: 'root'
      src: '99-xdebug.ini.j2'
    loop: '{{ webserver__xdebug_versions }}'
    notify: 'Reload PHP-FPM'
  when: webserver__xdebug_versions | length > 0
