# The following tasks installs and configures Xdebug.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Run Xdebug-related tasks'
  block:
  - name: 'Ensure Xdebug is installed'
    ansible.builtin.apt:
      force_apt_get: true
      name: 'php{{ webserver__php_version }}-xdebug'
      state: 'present'

  - name: "Ensure Xdebug's remote debugger is enabled"
    ansible.builtin.copy:
      content: 'xdebug.remote_enable=1'
      dest: '/etc/php/{{ webserver__php_version }}/fpm/conf.d/20-xdebug-remote-enable.ini'
      owner: 'root'
      group: 'root'
      mode: 0644
    notify: 'Reload PHP-FPM'
  when: webserver__install_xdebug
