# The following tasks installs and configures Xdebug.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Run Xdebug-related tasks'
  block:
  - name: 'Ensure Xdebug is installed'
    ansible.builtin.apt:
      force_apt_get: true
      name: 'php{{ webserver__php_version }}-xdebug'
      state: 'present'

  - name: 'Ensure custom Xdebug configuration file for PHP-FPM exists'
    ansible.builtin.template:
      dest: '/etc/php/{{ webserver__php_version }}/fpm/conf.d/99-xdebug.ini'
      group: 'root'
      mode: 0644
      owner: 'root'
      src: '99-xdebug.ini.j2'
    notify: 'Reload PHP-FPM'
  when: webserver__install_xdebug
