# This role installs and configures Canonical Livepatch.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure Canonical Livepatch is installed'
  community.general.snap:
    name: 'canonical-livepatch'
    state: 'present'

- name: 'Check Canonical Livepatch status'
  ansible.builtin.command: 'canonical-livepatch status --verbose'
  changed_when: false
  ignore_errors: true
  register: __livepatch_status

- name: 'Enable Canonical Livepatch'
  ansible.builtin.command: 'canonical-livepatch enable {{ livepatch__key }}'
  when: >
    __livepatch_status is defined
    and __livepatch_status.stdout is defined
    and 'Machine is not enabled.' in __livepatch_status.stdout
