# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Restart Fail2ban'
  ansible.builtin.service:
    name: 'fail2ban'
    state: 'restarted'

- name: 'Restart Monit'
  ansible.builtin.service:
    name: 'monit'
    state: 'restarted'

- name: 'Restart Prometheus Node Exporter'
  ansible.builtin.service:
    daemon_reload: true
    name: 'node_exporter'
    state: 'restarted'
