# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: Ensure the Certbot PPA is present in APT source list
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Ensure Certbot is installed
  apt:
    force_apt_get: yes
    name: python-certbot-apache

- name: Ensure the customised Certbot cron task is present
  replace:
    path: /etc/cron.d/certbot
    regexp: 'certbot -q renew$'
    replace: "certbot -q renew --webroot --webroot-path /var/www/html --renew-hook 'service apache2 graceful'"

- name: Ensure Certbot-issued certificates include the correct domain names
  script: "certbot-check.py {{ item.key }} {{ item.value.aliases | default([]) | join(' ') }}"
  args:
    executable: /usr/bin/python3
  register: certbot_update
  changed_when: certbot_update.stdout is search('Certificate')
  loop: "{{ sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
