# This role installs and configures Certbot.
#
# The following tasks effectively accomplishes the same thing as the
# "acme_certficate" Ansible module. However, using Certbot to manage
# certificates is a lot easier and Certbot also allows us to
# automatically renew certificates without any intervention.
#
# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
- name: 'Ensure Certbot is installed'
  community.general.snap:
    classic: true
    name: 'certbot'
    state: 'present'

- name: 'Get Certbot account status'
  ansible.builtin.command: 'certbot show_account'
  register: __certbot_show_account
  changed_when: false
  ignore_errors: true

# The previous task will have created "/etc/letsencrypt" and a few other
# directories inside it for us already.
- name: 'Ensure Certbot global configuration file exists'
  ansible.builtin.template:
    dest: '/etc/letsencrypt/cli.ini'
    group: 'root'
    mode: 0644
    owner: 'root'
    src: 'cli.ini.j2'

- name: 'Ensure custom logrotate configuration file for certbot logs exists'
  ansible.builtin.template:
    dest: '/etc/logrotate.d/certbot'
    group: 'root'
    mode: 0644
    owner: 'root'
    src: 'certbot.j2'
  when: '"monitoring" in ansible_play_role_names'

- name: "Ensure a Let's Encrypt ACME account has been registered"
  ansible.builtin.command:
    cmd: >
      certbot
      register
      --agree-tos
      --no-eff-email
      --email '{{ letsencrypt__administrator_email }}'
  when: letsencrypt__administrator_email not in __certbot_show_account.stdout

- name: "Ensure valid Let's Encrypt certificates for sites exist"
  ansible.builtin.script: 'certbot-check.py {{ item.key }} {{ item.value.aliases | default([]) | join(" ") }}'
  args:
    executable: '/usr/bin/python3'
  register: certbot_update
  changed_when: certbot_update.stdout is search('Certificate')
  ignore_errors: true
  loop: '{{ letsencrypt__sites | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  notify:
    'Reload Apache'

# This hook is not installed if logrotate is installed as Apache is
# already gracefully reloaded daily as part of log rotation gubbins.
- name: 'Ensure post-certificate-renewal Certbot hook exists'
  ansible.builtin.file:
    content: |
      #!/bin/bash
      # Ansible managed
      #
      # This file was written by Damien Dart, <damiendart@pobox.com>. This is
      # free and unencumbered software released into the public domain. For
      # more information, please refer to the accompanying "UNLICENCE" file.

      service apache2 graceful
    dest: '/etc/letsencrypt/renewal-hooks/post/reload-apache'
    mode: 0744
  when: '"monitoring" not in ansible_play_role_names'
