# This file was written by Damien Dart, <damiendart@pobox.com>. This is
# free and unencumbered software released into the public domain. For
# more information, please refer to the accompanying "UNLICENCE" file.

---
name: 'Lint Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: 'Lint project'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'

      - name: 'Set up Python environment'
        uses: 'actions/setup-python@v4'
        with:
          cache: 'pip'
          python-version: '3.8'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Install project dependencies and run all linting-related tasks'
        run: |
          ./bin/task start
          source .venv/bin/activate
          ./bin/task ci
